### ISSUE TITLE
Installing on UDM Pro

### ISSUE THREAD

**Issue by mbnn** [boostchicken/udm-utilities#1]
Hi, I was following your tutorial on on boot script (to be able to install Nextdns on my UDM Pro).
However, to the point where you say: systemctl enable udmboot
I keep getting: systemctl
-sh: systemctl: not found

Any idea? :) Running 1.7.0 on the UDM Pro.

**Comment by boostchicken** [comment]
This is because you are not in the container executing the command.  You get there with the podman exec -it sh command or by typing unifios-shell. 

I recommend just doing the automated way.  It will handle all of it for you.
