### ISSUE TITLE
Modularization updates

### ISSUE THREAD

**Issue by exodious** [boostchicken/udm-utilities#10]
**Is your feature request related to a problem? Please describe.**
This will probably be easier to maintain and extend if it were made slightly more modular. There are files repeated several times in the repository, which can require making the same updates in several places.

**Describe the solution you'd like**
There's a lot of commonality between the different solutions for adguardhome, nextdns, and pihole. They use the same cni plugin configuration and the on_boot script is basically the same as well.

It could also be made easier to extend for additional custom user functionality if a on boot script directory ala /etc/profile.d is used, such as /mnt/data/on_boot.d/*.sh.

**Describe alternatives you've considered**
N/A

**Additional context**
I've begun work on these changes for myself, and if you think this is worthwhile I can get a pull request together. See https://github.com/exodious/udm-utilities/tree/modularization-updates. I think it's basically just getting the README.md's updated that is left.

**Comment by boostchicken** [comment]
Hey @exodious .  Thanks for doing this.  I have been super busy with my personal life.  Regarding the ipv6 stuff I saw in your scripts, Podman doesn't support IPv6 from what I have seen.  Did you get it working?

Why don't you send a pull request over and I can help with README updates.

**Comment by boostchicken** [comment]
https://github.com/boostchicken/udm-utilities/pull/12

Done!

**Comment by exodious** [comment]
Awesome
