### ISSUE TITLE
HowTo Clean Uninstall?

### ISSUE THREAD

**Issue by mensa84** [boostchicken/udm-utilities#110]
Hello,

could you please explain, what is the correct way to do a clean uninstall of udm-utilities and also all installed scripts / projects / containers?
Or isn't that that easy to do?

**Comment by SturdyErde** [comment]
Complete steps to uninstall after in the wiki.
https://github.com/boostchicken/udm-utilities/wiki/Uninstall-UDM-Utilities-and-Containers
