### ISSUE TITLE
udm-boot_1.0.4_all.deb  "not a debian format archive"

### ISSUE THREAD

**Issue by foxyroxyrooster** [boostchicken/udm-utilities#115]
**Describe the bug**
Unable to install the 1.0.4 version. Multiple errors
unifios version 1.8.6 (latest stable)

1) Cert issue (mitigated by -k)

# unifi-os shell
root@ubnt:/# curl -L https://udm-boot.boostchicken.dev -o udm-boot_1.0.4_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

2)  Package issue. Unable to workaround.

root@ubnt:/# dpkg -i udm-boot_1.0.4_all.deb
[parse_pkg_files] cmdargs:  dpkg
dpkg-deb: error: 'udm-boot_1.0.4_all.deb' is not a debian format archive
dpkg: error processing archive udm-boot_1.0.4_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
#-> ubnt-dpkg-cache install
[parse_pkg_files] cmdargs:  dpkg
[cache_add_action] PKGFILES:  
<-# ubnt-dpkg-cache install
Errors were encountered while processing:
 udm-boot_1.0.4_all.deb

**Comment by boostchicken** [comment]
I just tested this @foxyroxyrooster and it works just fine.

```
# unifi-os shell
root@ubnt:/# curl -L https://udm-boot.boostchicken.dev -o udm-boot_1.0.4_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3320  100  3320    0     0   6298      0 --:--:-- --:--:-- --:--:--  6298
root@ubnt:/# dpkg -i u
udm-boot_1.0.4_all.deb  usr/
root@ubnt:/# dpkg -i udm-boot_1.0.4_all.deb
[parse_pkg_files] cmdargs:  dpkg
(Reading database ... 105528 files and directories currently installed.)
Preparing to unpack udm-boot_1.0.4_all.deb ...
Unpacking udm-boot (1.0.4) over (1.0.4) ...
Setting up udm-boot (1.0.4) ...
#-> ubnt-dpkg-cache install
[parse_pkg_files] cmdargs:  dpkg
[cache_add_action] PKGFILES:  /udm-boot_1.0.4_all.deb
```

**Comment by boostchicken** [comment]
I noticed an SSL certificate error, check the contents of the deb file and make sure your are not getting some weird error there, also try just regular http

**Comment by foxyroxyrooster** [comment]
Retried with HTTP. Still complains about the package:

root@ubnt:/# curl -L http://udm-boot.boostchicken.dev -o udm-boot_1.0.4_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   297  100   297    0     0  12951      0 --:--:-- --:--:-- --:--:-- 13500
root@ubnt:/# ls 
bin   data  etc       home  media  opt   root  sbin  sys  udm-boot_1.0.4_all.deb  var
boot  dev   etc_host  lib   mnt    proc  run   srv   tmp  usr
root@ubnt:/# dpkg -i u
udm-boot_1.0.4_all.deb  usr/                    
root@ubnt:/# dpkg -i u
udm-boot_1.0.4_all.deb  usr/                    
root@ubnt:/# dpkg -i udm-boot_1.0.4_all.deb 
[parse_pkg_files] cmdargs:  dpkg
dpkg-deb: error: 'udm-boot_1.0.4_all.deb' is not a debian format archive
dpkg: error processing archive udm-boot_1.0.4_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2

I do have the older version running just fine BTW (even after the 1.8.6 upgrade, multiple reboots happened and still no issues):

root@ubnt:/# dpkg -l | grep udm                    
ii  udm-boot                             1.0.2                                                     all          Run things on boot on UDM

However the 0.0.4 is not happy:

root@ubnt:/# ls -alh udm-boot_1.0.4_all.deb 
-rw-r--r-- 1 root root 297 Feb  3 07:46 udm-boot_1.0.4_all.deb

root@ubnt:/# dpkg -c udm-boot_1.0.4_all.deb 
dpkg-deb: error: 'udm-boot_1.0.4_all.deb' is not a debian format archive

**Comment by peacey** [comment]
foxyroxyrooster, have you tried to just download the package on your computer and then transfer it to the UDM via scp/sftp?

Using curl works fine for me and the package is not corrupted. So there is clearly something wrong on your end.

**Comment by foxyroxyrooster** [comment]
Not sure why using -s option with curl here - will suppress all noise, including the errors.
Odd thing is that all other .deb files show up just fine, except the subj.
Even tried wget. Same corrupt file. I give up.

root@ubnt:/var/tmp# wget http://udm-boot.boostchicken.dev/udm-boot_1.0.4_all.deb
--2021-02-03 16:39:14--  http://udm-boot.boostchicken.dev/udm-boot_1.0.4_all.deb
Resolving udm-boot.boostchicken.dev (udm-boot.boostchicken.dev)... 162.159.36.12, 162.159.46.12, 2606:4700:54::a29f:240c, ...
Connecting to udm-boot.boostchicken.dev (udm-boot.boostchicken.dev)|162.159.36.12|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 297
Saving to: 'udm-boot_1.0.4_all.deb'

udm-boot_1.0.4_all.deb    100%[===================================>]     297  --.-KB/s    in 0s      

2021-02-03 16:39:14 (48.5 MB/s) - 'udm-boot_1.0.4_all.deb' saved [297/297]

root@ubnt:/var/tmp# ls
index.html  udm-boot_1.0.4_all.deb
root@ubnt:/var/tmp# dpkg -c udm-boot_1.0.4_all.deb 
dpkg-deb: error: 'udm-boot_1.0.4_all.deb' is not a debian format archive

**Comment by Archerious** [comment]
Same issue

**Comment by Archerious** [comment]
Resolved it by using http instead of https.

**Comment by foxyroxyrooster** [comment]
I was able to workaround by downloading the .deb to my local drive > UDM host OS /mnt/persistent/ folder then accessing it from unifios shell and installing with no errors

**Comment by russellkeenan** [comment]
I hit the same error with 1.0.7. 
File output produced by command:
  curl -L https://unifi.boostchicken.io/udm-boot_1.0.7_all.deb -o udm-boot_1.0.7_all.deb
was only 162 bytes.
Fix was to download file through a browser, then upload to UDMPRO.
