### ISSUE TITLE
OpenVPN Client as "VPN Gateway"

### ISSUE THREAD

**Issue by traktuner** [boostchicken/udm-utilities#117]
Hello,
I am currently using a docker container on my NAS as a VPN-Gateway, it's IP is the gateway address of all my LAN and WiFi devices, so that all outside traffic is encrypted.
I think that an OpenVPN client is already installed on the UDM-Pro but not directly user accessible.
Is there a way you can implement this functionality with the boot script or a container?
My goal would be to normally direct the traffic to the UDM-Pro IP address that I don't need my VPN docker container anymore.
Unfortunately, my VPN provider only supports OpenVPN and IKEv2.
Thank you for maintaining this great project!

**Comment by Tntdruid** [comment]
I use https://www.zerotier.com/ for that. :)

**Comment by traktuner** [comment]
> I use https://www.zerotier.com/ for that. :)

Thanks :) But unfortunately that's not an option for me.

**Comment by peacey** [comment]
> Hello,
> Is there a way you can implement this functionality with the boot script or a container?

Hi, I have a project that does this here via a custom script that can be used with the on-boot-script: https://github.com/peacey/split-vpn

Don't mean to advertise my project on this board, but I might do a pull request for my project to be added to this if there is interest.

**Comment by traktuner** [comment]
> > Hello,
> > Is there a way you can implement this functionality with the boot script or a container?
> 
> Hi, I have a project that does this here via a custom script that can be used with the on-boot-script: https://github.com/peacey/split-vpn
> 
> Don't mean to advertise my project on this board, but I might do a pull request for my project to be added to this if there is interest.

cool, thank you! Is your implementation using the native openvpn client? 
If yes I will give it a try when I have the time!

**Comment by peacey** [comment]
> cool, thank you! Is your implementation using the native openvpn client?
> If yes I will give it a try when I have the time!

Yes, it is using the openvpn client already installed. It is just a helper script for the openvpn client that adds iptables rules and policy-based routes to force specified clients through the VPN. The script is used via the --up and --down options of OpenVPN.

**Comment by traktuner** [comment]
@peacey Your script works flawlessly, also on boot. Everything somebody could ask for.
Thank you!
