### ISSUE TITLE
Possibly stops adoption/detection of new cameras in Unifi Protect

### ISSUE THREAD

**Issue by rkydd** [boostchicken/udm-utilities#118]
I recently added a new camera and could not get the camera to be identified/adopted by Protect. Several reboots, firmware updates and lots of retries later, I rebooted the UDM-Pro without the on_boot.sh triggering (I renamed it before a udm reboot) and the camera was detected and adopted straight away.

My on_boot.sh and contents of on_boot.d just contain the dns/pihole network config. My guess is something in there has adjusted the ifconfig to intercept messages that also are looked for by Protect. Its beyond my abilities to understand this one quickly, so I am hoping someone else may have more knowledge to explain.....

If not, I will do some learning and see if I can diagnose better.

Apologies if I am making an incorrect assumption, but hopefully this will help others.

**Comment by SparkDustJoe** [comment]
If the only config changes you've made inthe boot script is to "iptable" port 53 traffic, then the PiHole may be what's interfering if the Protect subsystem and/or the camera is trying to DNS somewhere.  You might see entries in the PiHole that would indicate that.  The other alternative is to disable the Pi through the admin panel (which just passes all traffic through without blocking or 127'ing any address).  Try that and see if Protect picks up the new camera.

**Comment by foxyroxyrooster** [comment]
In my experience omitting the whole iptable redirect of Port 53 is the best option.
It definitely breaks things around and is quite pointless unless you have unruly and tech savvy users on your network that capable of configuring their own DNS client setting this bypassing pihole/adguard/nextdns

**Comment by wmandra** [comment]
It's definitely not the on_boot script itself as I have it running with AdGuardHome and had no issues adopting new cameras since. 

Rather than the iptable redirect, I just have firewall rules that allow DNS from clients to my Adguard instance and block all other destination on TCP/UDP port 53.
