### ISSUE TITLE
Pihole installation - All client origins are from VLAN router

### ISSUE THREAD

**Issue by nicholas-c** [boostchicken/udm-utilities#127]
**Describe the bug**
Using standard installation method outlined in the pihole folder, when viewing query logs in pihole admin, all query's are from the same origin (192.168.3.1 in my case, VLAN 3)

**To Reproduce**
1. Follow steps for "standard" pihole installation on UDM Pro
2. View Query logs on pihole admin panel
3. All client queries come from 192.168.3.1

**Expected behavior**
Query logs should contain the origin device IP address (Would help with debugging where queries are coming from, e.g malicious devices)

**UDM Information**
 - UDM Pro
 - 1.8.6
 - 6.0.43

**Comment by peacey** [comment]
I do not have this bug, so seems like a problem with your configuration. Can you check the following?

1. Did you set up your clients to use the pihole IP directly as their DNS by changing the LAN network DNS settings on either the Unifi Network or the client directly? Can you check what DNS your clients are being assigned?

2. Are you using the `FORCED_INTFC" option? If you are, the clients/interface you force have to be on a different subnet/VLAN than the pihole. You cannot force br3. 

3. Do you have any extra firewall rules doing a MASQUERADE for port 53? A port forward might add such a rule. Check your iptables rules with `iptables -t nat -S | grep MASQUERADE`

**Comment by nicholas-c** [comment]
1) My clients are using the default gateway IP as their DNS server (Laptop being `192.168.0.1` as example) - In the UDM Pro settings I set the WAN Network to use DNS server of `192.168.3.2`.
2) This option in 10-dns.sh is empty
3) I have a few port forwarding rules for unrelated ports (8123, 1194) but nothing for 53 

```# iptables -t nat -S | grep MASQUERADE | grep 53
#```

**Comment by peacey** [comment]
> 1. My clients are using the default gateway IP as their DNS server (Laptop being `192.168.0.1` as example) - In the UDM Pro settings I set the WAN Network to use DNS server of `192.168.3.2`.

That's probably the issue then. You're supposed to change the LAN DNS settings, not WAN. Your clients are supposed to get pihole DNS via DHCP.

Changing the WAN DNS sets the router to use the pihole DNS, but the clients are still using the router, so the router is forwarding the requests. You need to change it in the LAN DNS settings for your LANs you want to use the pihole.

**Comment by nicholas-c** [comment]
That'll be it! Thanks @peacey seems to have fixed it. I'll have a play with FORCED_INTFC too :) 

Highly appreciated
