### ISSUE TITLE
101 install notes on installing UDM-Utilities

### ISSUE THREAD

**Issue by APDODD** [boostchicken/udm-utilities#128]
Trying to install the conditional DNS scripts on my UDMPro and have followed the first part of manually creating the scripts that work.... Now I want to install this as a service but can't get my head around the installing of the onboot.d service.

It would be great if there was a know how post to get this installed so we can take advance of this super add-on for the UDM/UDMPro.

Thanks in advance
Andrew

**Comment by SturdyErde** [comment]
Here is the documentation. Follow the readme under the Steps section. https://github.com/boostchicken/udm-utilities/blob/master/on-boot-script/README.md#steps

**Comment by APDODD** [comment]
> Here is the documentation. Follow the readme under the Steps section. https://github.com/boostchicken/udm-utilities/blob/master/on-boot-script/README.md#steps

StrurdyErde,

When I run the installer
curl -L https://udm-boot.boostchicken.dev -o udm-boot_1.0.4_all.deb
dpkg -i udm-boot_1.0.4_all.deb
exit

I get the following.. 

curl -L https://udm-boot.boostchicken.dev -o udm-boot_1.0.4_all.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3320  100  3320    0     0  27899      0 --:--:-- --:--:-- --:--:-- 27899
# dpkg -i udm-boot_1.0.4_all.deb
-sh: dpkg: not found

I'm the first to admit that I'm no Linux guy and this is  why I'm asking for an install guide

**Comment by peacey** [comment]
APDODD, you didn't follow Step 1 in the guide. First type `unifi-os shell`. This puts you into the Unifi-OS container that has the dpkg command. Run the curl/dpkg commands after you type that first.

The installation is like 3 steps and the guide covers it pretty well.
