### ISSUE TITLE
Pi Hole's connection is almost non existent.

### ISSUE THREAD

**Issue by glahera** [boostchicken/udm-utilities#13]
**Describe the bug**

**To Reproduce**
1. Creating a CNI network with VLAN ID 30, same with the one created in Unifi
2. Run Pi-Hole container
3. Unable to connect to Pi-Hole

**Expected behavior**
Able to at least ping to Pi-Hole's IP from UDM

**Screenshots**

**UDM Information**
 - Variant: UDM
 - Firmware Version: 1.7.0
 - Controller Version: 5.13.27

**Additional context**
Hello, and thank you for your amazing works (seems like everybody's getting it working). I think I made a mistake somewhere and now I don't have anyway to fix it. I have the corporate network created with 192.168.6.0/26 and VLAN ID 30. Then I modified the file 10-dns.sh and 20-dns.conflist accordingly with that, now podman is reporting everything is working fine but I can't ping to container's IP from UDM, and I can't ping to outside container from PiHole container.

**Comment by boostchicken** [comment]
Can you post your files?  Can't really tell you much unless I see how it's configured.

**Comment by kphonik** [comment]
I'm having the same issue - wondering if this is related to not setting a value in `FORCED_INTFC`. Here are the values from my latest attempt today:

```bash
VLAN=3                                                                                                                  
IPV4_IP="172.16.3.53"                                                                                                   
IPV4_GW="172.16.3.1/24"                                                                                                 
CONTAINER=pihole                                                                                                        
```

```json
{
  "cniVersion": "0.4.0",
  "name": "dns",
  "plugins": [
    {
      "type": "macvlan",
      "mode": "bridge",
      "master": "br3",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "172.16.3.53/24",
            "gateway": "172.16.3.1"
          }
        ],
        "routes": [
          {"dst": "0.0.0.0/0"}
        ]
      }
    }
  ]
}
```

**Comment by kphonik** [comment]
Baaahahaha I spoke too soon - it worked this time :-) Thanks for the effort @boostchicken - this weekend I finally got wpa_supplicant working and now I can move pihole on the udm. Much appreciated!!

**Comment by boostchicken** [comment]
@kphonik gave you a present, this stuff persists through firmware updates now.  Right when you got it setup, I change it on you :)

**Comment by boostchicken** [comment]
Also, could you post the solution for others?

**Comment by kphonik** [comment]
@boostchicken I'm not sure what the solution was. I did notice my first attempt did not correctly set the `plugins.master` value in the cni config file. I had left it as `br5` instead of `br3` to match my vlan. I'm not sure if this was in the instructions or just implicit.

**Comment by boostchicken** [comment]
@glahera If I don't hear from you in a couple days I will close the issue assuming you got it fixed.
