### ISSUE TITLE
Stopping downstream switches from seeing Pihole as a "client"

### ISSUE THREAD

**Issue by orcinus** [boostchicken/udm-utilities#143]
I realize this isn't a udm-utilities or pihole bug, but i doubt i'll get any help from Unifi, so posting here on the off chance someone experienced something similar or has an idea... Please close/delete if necessary.

My setup looks like this:
- UDM-Pro
- USW-Pro-24-PoE
- USW-Flex
- U6-Lite

There are two networks:
- 192.168.2.0/24
- 192.168.5.0/24, VLAN 10

Everything's on the 192.168.2.0/24 network.
Pihole is running on the UDM-Pro on the VLAN 10 network.

https://img.community.ui.com/bc5cebd1-d0e0-4b8f-9834-3c6debe293c4/questions/033a3fe1-fb6b-4033-9aa7-2057e736d4be/ebeee13f-a899-4411-ad35-3fc46b9aa1ff

For some reason, USW-Flex keeps reporting the Pihole virtual MAC addresses as its "clients", connected to port #1 (i.e. USW-Flex' uplink), which is nonsensical on multiple levels. They keep showing up and disappearing many times a day. Does anyone have any idea how to stop it?

It seems to only affect USW-Flex, to make things even weirder.

**UDM Information**
 - Dream Machine Pro
 - Firmware Version: 1.9.1
 - Controller Version: 6.1.67

**Comment by orcinus** [comment]
Temp fix - i've killed all VLANs on all the ports leading to the USW-Flex, and that stops it as expected, but... i mean... that's more like a bandaid. In fact, i could've sworn i already did that on the Flex uplink port, but that didn't seem to work until i cut off the pihole VLAN from all the upstream ports as well.

Bizarreness.

**Comment by peacey** [comment]
Happens to me too, not just with the pihole network, but also with all the macvlan networks I have, and VLAN-only networks. They appear and disappear every 5 minutes (exactly). It seems that there is a service on the OS that is discovering them through the neighbour table (`ip neigh`) every 5 minutes, and it doesn't really know where they're coming from, so it misclassifies them as coming from some random switch or the closest subnet or something like that. 

It doesn't seem there's much we can do as Ubiquiti has to fix how they classify devices from the neighbour table. I've ended up naming each one (by adding their MAC as a client) like "Pihole", "Network Services VLAN5", etc, so I can know if it's just those devices or some rogue device on my network.

**Comment by orcinus** [comment]
Good idea, thank you!
Think i'll do the same.
