### ISSUE TITLE
Installing 2nd container, how to add to 10-dns.sh

### ISSUE THREAD

**Issue by marceldarvas** [boostchicken/udm-utilities#145]
I was checking these response, but I was not able to figure out how I add additional containers to my 10-dns.sh

This is where I get stuck:
`# podman container start nextdns
nextdns
# podman container start homebridge
ERRO[0000] Error adding network: failed to allocate for range 0: no IP addresses available in range set: 10.0.5.10-10.0.5.10 
ERRO[0000] Error while adding pod to CNI network "homebridge": failed to allocate for range 0: no IP addresses available in range set: 10.0.5.10-10.0.5.10 
Error: unable to start container "homebridge": error configuring network namespace for container 6fafed34b9811c15e9896df23a66358b7bf4ac47c4139a555e1ab18b662ec40e: failed to allocate for range 0: no IP addresses available in range set: 10.0.5.10-10.0.5.10`

I have NextDNS running at 10.0.5.3.

I've even tried creating br6 after br5 was just not handing me an IP for homebridge instance.

Could someone please assist?

@ghvader you can add as many containers as you want to a single macvlan network. All that is required is learning the CNI plugins.  If you look at our CNI plugins we use the static ip ipam provider.  There are others for dhcp, handing out ips from a local range etc etc.  Just look at the CNI driver documentation and adjust accordingly

https://github.com/boostchicken/udm-utilities/blob/master/cni-plugins/20-dns.conflist

_Originally posted by @boostchicken in https://github.com/boostchicken/udm-utilities/issues/66#issuecomment-751126807_

**Comment by boostchicken** [comment]
@marceldarvas just make a new 20-dns.conf like 21-dns.conf, make sure it has a different ip and name, and then on start make make sure you route the new ip.  its kinda weird to describe but its easy enough. to do if you are up foir a screen share, join slack or hit me on discord
