### ISSUE TITLE
Add support for Digital Ocean Dynamic DNS

### ISSUE THREAD

**Issue by MadD0c** [boostchicken/udm-utilities#147]
I have been looking for a way to update your IP address to Digital Ocean as it is not supported via the UDM UI. On researching this there has been very little options to do it even via the previous config.gateway.json file.

I have managed to achieve a solution similar to the Cloudflare solution here. I have done this using the UNIX daemon by alcroito (https://github.com/alcroito/digitalocean-dyndns) which he has also released in a containerized form. I have put what I have done so far up here (https://github.com/MadD0c/digitalocean-ddns).

Please let me know if you would like to include it in this collection and I will create a pull request and add it in.

**Comment by boostchicken** [comment]
please do!
