### ISSUE TITLE
unifi-os restart doesn't work from an on-boot script

### ISSUE THREAD

**Issue by klemens-st** [boostchicken/udm-utilities#148]
**Describe the bug**
While trying to debug unifi-os stopping and not restarting while executing the [udm-le on boot script](https://github.com/kchristensen/udm-le/blob/a3f2b922e4fa5d7862511e73c74584330dd6873c/on_boot.d/99-udm-le.sh), I realised that when I put `unifi-os restart` in an on boot script, it stops unifi-os and exits, doesn't start it back up.

**To Reproduce**
1. Create a new script in /mnt/data/on_boot.d:
```shell
#!/bin/sh

sleep 300
unifi-os restart
```
2. Reboot UDM-PRO.
3. After 5 minutes unifi-os will be stopped but won't start.

**Expected behavior**
The script should restart unifi-os the same way as if it was run from command line. Note: It **does** work from command line.

**UDM Information**
 - Variant: Dream Machine Pro
 - Firmware Version: 1.9.0
 - Controller Version: 6.1.61

**Additional context**
It has been discussed in detail in [this udm-le issue](https://github.com/kchristensen/udm-le/issues/29), especially in this [comment containing test results and logs](https://github.com/kchristensen/udm-le/issues/29#issuecomment-799790806)

**Comment by LaurenceJJones** [comment]
Just adding this but I'm running standard UDM and get the same issues if it makes any difference.

**Comment by emlynmac** [comment]
Do you mean that if you run `UniFi-OS restart` From your ssh prompt, it doesn’t work for you?

For me, the restart only fails when executed from the context of the on-boot scrtipts; running from the main shell via ssh works fine

**Comment by chriscpritchard** [comment]
For me it's only when executed from the context of a boot script (UDM base user here), as a temporary workaround I disabled the restart within the on-boot script as I figured it would pick it up when the cronjob runs (and it seems only the captive portal actually needs the restart as the LE cert seems to persist across reboots for the controller interface)

**Comment by klemens-st** [comment]
> Do you mean that if you run UniFi-OS restart From your ssh prompt, it doesn’t work for you?

No, I meant that it works from ssh but doesn't when executed by the on-boot script.

**Comment by jinkang23** [comment]
i have the same issue as well. Been having it ever since 1.8.6. Running 1.9.2 now and issue still persist.

**Comment by peacey** [comment]
It doesn't work because the unifi-os command, which is run in a process within the container, wants to write to an output but is interrupted when the container shuts down. This causes the process to crash before it can run the start command (hence the container stops but doesn't start again). The solution is to redirect output to /dev/null or a file. It's better to add a `&` after the command to run it in the background too so it doesn't get affected by the container closing. 

This works for me to restart the container from a boot script:

```sh
unifi-os restart &>/dev/null &
```

Alternatively, you can also use podman to restart the container within the boot script by running it in the background too,

```sh
podman restart unifi-os &
```

**Comment by emlynmac** [comment]
Just tested this with my local set up - changed the values to the `podman restart unifi-os &` suggested. 
Seems to be working fine now - thanks @peacey

**Comment by jinkang23** [comment]
> ```shell
> ```shell
> unifi-os restart &>/dev/null &
> ```
> ```

I tested the setup on udm-pro 1.9.2 using the value `unifi-os restart &>/dev/null &` and it worked! - thank you @peacey !

**Comment by klemens-st** [comment]
Thanks @peacey! Closing the issue, I guess this is the expected behavior since boot scripts are run from within a container.
