### ISSUE TITLE
Network unreachable after installation

### ISSUE THREAD

**Issue by mhus** [boostchicken/udm-utilities#150]
**Describe the bug**
I installed AdguardHome as described.

After installation 10.0.5.3 is not reachable. But I'm able to ping 10.0.5.1.

Executing /mnt/data/on_boot.d/10-dns.sh

Prints:

ip: either "local" is duplicate, or "noprefixroute" is garbage
podman-dns: Container adguardhome not found, make sure you set the proper name, you can ignore this error if it is your first time setting it up

Second line is ok, but the 'ip:' line is maybe a problem (?).

Here are some infos:

# ip route list
10.0.5.0/24 dev br5 scope link  src 10.0.5.1 
10.0.5.3 dev br5.mac scope link 
10.42.10.0/23 dev br0 scope link  src 10.42.10.10 
10.43.50.0/24 via 10.42.10.30 dev br0  metric 1 
62.155.243.205 dev ppp0 scope link  src 79.238.26.67 

# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop 
    link/ether ae:33:6e:e8:7f:16 brd ff:ff:ff:ff:ff:ff
3: eth9: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq qlen 10000
    link/ether f4:92:bf:77:94:20 brd ff:ff:ff:ff:ff:ff
4: eth8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq qlen 1000
    link/ether f4:92:bf:77:94:1f brd ff:ff:ff:ff:ff:ff
5: eth10: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq master br0 qlen 10000
    link/ether f4:92:bf:77:94:21 brd ff:ff:ff:ff:ff:ff
6: switch0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq qlen 1000
    link/ether f6:92:bf:77:94:17 brd ff:ff:ff:ff:ff:ff
7: gre0@NONE: <NOARP> mtu 1476 qdisc noop 
    link/gre 0.0.0.0 brd 0.0.0.0
8: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
9: ip_vti0@NONE: <NOARP> mtu 1364 qdisc noop 
    link/ipip 0.0.0.0 brd 0.0.0.0
10: sit0@NONE: <NOARP> mtu 1480 qdisc noop 
    link/sit 0.0.0.0 brd 0.0.0.0
11: br0: <BROADCAST,MULTICAST,UP,LOWER_UP100> mtu 1500 qdisc noqueue 
    link/ether f6:92:bf:77:94:17 brd ff:ff:ff:ff:ff:ff
12: eth0@br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue 
    link/ether f4:92:bf:77:94:17 brd ff:ff:ff:ff:ff:ff
13: eth1@br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue 
    link/ether f4:92:bf:77:94:18 brd ff:ff:ff:ff:ff:ff
14: eth2@br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue 
    link/ether f4:92:bf:77:94:19 brd ff:ff:ff:ff:ff:ff
15: eth3@br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue 
    link/ether f4:92:bf:77:94:1a brd ff:ff:ff:ff:ff:ff
16: eth4@br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue 
    link/ether f4:92:bf:77:94:1b brd ff:ff:ff:ff:ff:ff
17: eth5@br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue 
    link/ether f4:92:bf:77:94:1c brd ff:ff:ff:ff:ff:ff
18: eth6@br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue 
    link/ether f4:92:bf:77:94:1d brd ff:ff:ff:ff:ff:ff
19: eth7@br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue 
    link/ether f4:92:bf:77:94:1e brd ff:ff:ff:ff:ff:ff
20: ifb0: <BROADCAST,NOARP> mtu 1500 qdisc noop qlen 32
    link/ether 12:a8:d6:b7:78:b3 brd ff:ff:ff:ff:ff:ff
21: ifb1: <BROADCAST,NOARP> mtu 1500 qdisc noop qlen 32
    link/ether 2a:73:ed:7d:a8:8a brd ff:ff:ff:ff:ff:ff
22: br5: <BROADCAST,MULTICAST,UP,LOWER_UP100> mtu 1500 qdisc noqueue 
    link/ether f4:92:bf:77:94:21 brd ff:ff:ff:ff:ff:ff
23: eth10.5@eth10: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue master br5 
    link/ether f4:92:bf:77:94:21 brd ff:ff:ff:ff:ff:ff
24: switch0.1@switch0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 
    link/ether f6:92:bf:77:94:17 brd ff:ff:ff:ff:ff:ff
25: switch0.5@switch0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br5 
    link/ether f6:92:bf:77:94:17 brd ff:ff:ff:ff:ff:ff
26: ppp0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1492 qdisc pfifo_fast qlen 3
    link/ppp 
27: br5.mac@br5: <BROADCAST,MULTICAST,UP,LOWER_UP100> mtu 1500 qdisc noqueue 
    link/ether 16:40:f2:75:34:6a brd ff:ff:ff:ff:ff:ff
# 

# podman ps
CONTAINER ID  IMAGE                                 COMMAND               CREATED         STATUS             PORTS  NAMES
1c8158d4b1ff  localhost/unifi-os:current            /sbin/init            24 minutes ago  Up 24 minutes ago         unifi-os
8bec57b71320  docker.io/adguard/adguardhome:latest  --no-check-update...  25 minutes ago  Up 24 minutes ago         adguardhome
# 

# podman logs adguardhome
2021/03/25 23:05:13 [error] Couldn't read config file /opt/adguardhome/conf/AdGuardHome.yaml: open /opt/adguardhome/conf/AdGuardHome.yaml: no such file or directory
2021/03/25 23:05:13 [info] AdGuard Home, version v0.105.2, channel release, arch linux arm64
2021/03/25 23:05:13 [info] This is the first time AdGuard Home is launched
2021/03/25 23:05:13 [info] Checking if AdGuard Home has necessary permissions
2021/03/25 23:05:13 [info] AdGuard Home can bind to port 53
2021/03/25 23:05:13 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
2021/03/25 23:05:13 [info] Auth: initialized.  users:0  sessions:0
2021/03/25 23:05:13 [info] Initialize web module
2021/03/25 23:05:13 [info] This is the first launch of AdGuard Home, redirecting everything to /install.html 
2021/03/25 23:05:13 [info] AdGuard Home is available on the following addresses:
2021/03/25 23:05:13 [info] Go to http://127.0.0.1:3000
2021/03/25 23:05:13 [info] Go to http://[::1]:3000
2021/03/25 23:05:13 [info] Go to http://10.0.5.3:3000
# 

Executing wget will cause a network unreachable, but this could be ok on the host:
# wget -O - http://10.0.5.3:3000
Connecting to 10.0.5.3:3000 (10.0.5.3:3000)
wget: can't connect to remote host (10.0.5.3): No route to host
# 

from another system:
$ ping 10.0.5.3       
PING 10.0.5.3 (10.0.5.3): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
92 bytes from unifi.localdomain (10.42.10.10): Destination Host Unreachable
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 97eb   0 0000  3f  01 bf2b 10.42.11.102  10.0.5.3 

$  wget -O - http://10.0.5.3:3000
--2021-03-26 00:31:24--  http://10.0.5.3:3000/
Connecting to 10.0.5.3:3000... failed: Network is unreachable.

**Comment by mhus** [comment]
Maybe you have got a hint to fix it. Thx!

**Comment by boostchicken** [comment]
Have you tried jumping in the container and seeing if it has connectivity at all?

here is my list, also please show us your 10-dns.sh 

```
10.0.0.0/24 dev br0 proto kernel scope link src 10.0.0.1
10.0.1.0/25 dev br10 proto kernel scope link src 10.0.1.1
10.0.5.0/24 dev br5 proto kernel scope link src 10.0.5.1
10.0.5.0/24 dev br5.mac proto kernel scope link src 10.0.5.1
10.0.5.3 dev br5.mac scope link
```

Also, give us an ifconfig out.

**Comment by mhus** [comment]
Sorry for delay: After updating the UDM the script is running. Thx!
