### ISSUE TITLE
Update WireGuard-Go version?

### ISSUE THREAD

**Issue by jaegerschnitzel** [boostchicken/udm-utilities#155]
Unfortunately WireGuard-Go version is 0.0.20200320.

How can I get the latest version running? masipcat also updated the package (https://github.com/masipcat/wireguard-go-docker) so I'm a bit confused why the old version is running with this script. Hope that someone can help me.

 - UDM-PRO
 - Firmware Version: 1.9.2

**Comment by boostchicken** [comment]
Please change the label to masipcat/wireguard-go:latest-arm64v8.  It seemes he pusshed the wrong image to :latest

**Comment by jaegerschnitzel** [comment]
Unfortunately that does not help. My Wireguard-Go version is still stuck on 0.0.20200320

**Comment by boostchicken** [comment]
@jaegerschnitzel did you do a podman rmi and then try again? What is your start script say?

**Comment by boostchicken** [comment]
Also I forgot, please stop and make sure the container is removed completely.

**Comment by jaegerschnitzel** [comment]
> docker rmi docker.io/masipcat/wireguard-go:latest

Thanks that fixed it :)
