### ISSUE TITLE
3CX in a container?

### ISSUE THREAD

**Issue by smegoff** [boostchicken/udm-utilities#157]
As we know, the voice side of the UDM Pro is very immature - to the point of non-existent. 

How about 3CX on the UDM Pro?

https://www.3cx.com/community/threads/3cx-inside-docker-container.52232/

Something to consider?

**Comment by boostchicken** [comment]
If 3cx has an arm64 package the answer is absolutely yes, it would follow the same pattern as the dns containers (macvlan).  Also, how much compue power does it need?

**Comment by boostchicken** [comment]
Some quick digging, the vendor does not supply at arm64 build package for us the build off of. Just cheked and found their amd64.  There are binaries on the RPi package, but those are tailored to RPi (32bit stuff)
