### ISSUE TITLE
Pi-Hole on untagged VLAN

### ISSUE THREAD

**Issue by PsychoRS** [boostchicken/udm-utilities#159]
Hi,

What if I need my Pi-Hole on the same network (no VLANs) than the rest of my setup (192.168.1.x)? Is there any way that doesn't involve creating VLAN's for that specific container?

Thanks

**Comment by boostchicken** [comment]
sure, just put VLAN of "0" and make sure your ip address its going to use is outside of the DHCP range.

**Comment by boostchicken** [comment]
honestly though, i would have it on its own vlan for security reasons

**Comment by nicx** [comment]
@boostchicken could you explain a little bit more your thoughts about "own vlan for security reasons"?

I plan to setup an AdguardHome container in my native VLAN 0, too, where all my "standard" network equipment resists, including a NAS with open ports to/from the "devil" internet (firewall port forwarding).

I have other separated VLANs for IOT stuff and guests, but as DNS is a very central service I have no idea why to separate it into an extra network, with extra complexity and extra firewall rules etc.. ;)
