### ISSUE TITLE
Wireguard - tunnel is up but can't reach anything.

### ISSUE THREAD

**Issue by htilly** [boostchicken/udm-utilities#161]
**UDM Information**
 - Dream Machine Pro
 - Firmware Version: 1.9.3.3438
 - Controller Version: 1.9.3

Hi!

Need some help with routing / iptables I guess. 
Everything seems to be up and running and I can connect from two clients in to the container (wireguard). But once connected everything stops. Can't even ping local address.
Created a dedicated network for WireGuard and all routing etc from within the container works. I.e. I can ping 8.8.8.8 and UDM itself. 
What am I missing?

**Server Conf:**

```
Interface]
# Change to map to your subnet
Address = 172.16.201.253/24
PrivateKey = _SERVER_PRIVAT_KEY_
# Can be whatever port you like
ListenPort = 51820

## Does not make a difference...
# PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o br2 -j MASQUERADE   
# PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o br2 -j MASQUERADE

[Peer]
PublicKey = _CLIENT_PUBLIC_KEY_
# Change to the CIDRs you want routed over the VPN
AllowedIPs = 172.16.201.10/32

[Peer]
PublicKey = _CLIENT_PUBLIC_KEY_
AllowedIPs = 172.16.201.11/32
```

**Client Conf:**

```
[Interface]
PrivateKey = _CLIENT_PRIVATE_KEY_
Address = 172.16.201.11/32
DNS = 172.16.200.1

[Peer]
PublicKey = _CLIENT_PRIVATE_KEY_
AllowedIPs = 0.0.0.0/0
Endpoint = _PUBLIC_IP_OF_UDM:51820
PersistentKeepalive = 25
```

**On UDM:**

_podman exec -it wireguard wg_ 

interface: wg0
  public key: _KEY_
  private key: (hidden)
  listening port: 51820

peer: _KEY_
  endpoint: 172.16.200.79:52549
  allowed ips: 172.16.201.11/32
  latest handshake: 3 minutes, 54 seconds ago
  transfer: 54.21 KiB received, 948 B sent

peer: _KEY_
  endpoint: 78.77.197.81:30821
  allowed ips: 172.16.201.10/32
  latest handshake: 6 minutes ago
  transfer: 33.86 KiB received, 1012 B sent

  Unable to ping ANY adress from the client.
  Non of the "local" IPs respond to ping (172.16.201.253 or 172.16.201.11)

**Comment by boostchicken** [comment]
did you check ips/ids and your firewall?

**Comment by boostchicken** [comment]
Re-open if you still need help

**Comment by bobsoppe** [comment]
I am having the same issue as @htilly where I want to set up a server to connect to from a remote location so that I am able to access my lan client.

For this I have the following config

```[Interface]
Address = 192.168.20.2/24
ListenPort = 51820
PrivateKey = <private_key>
PostUp =   iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth8 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth8 -j MASQUERADE

[Peer]
PublicKey = <public_key>
AllowedIPs = 192.168.20.111/32
```

Can you help me with setting this up correctly?
