### ISSUE TITLE
[Feature Request] Support for running scripts in a detached method.

### ISSUE THREAD

**Issue by kalenarndt** [boostchicken/udm-utilities#162]
**Is your feature request related to a problem? Please describe.**
I wrote a script that runs in the background and monitors the interfaces on the UDM Pro. Current on_boot.sh runs the shell scripts in a non-detached way

**Describe the solution you'd like**
Modifications to on_boot.sh on line 6 to do the following
                        . $i &

**Describe alternatives you've considered**
I have considered using wrapper scripts in the on_boot.d directory that would then call my other script but then this requires maintaining multiple files for 1 solution. 

**Additional context**
Here is a link to the current script and modifications that I have made https://github.com/kalenarndt/udmp-jumbo-frames

**Comment by boostchicken** [comment]
This would break script ordering and allow multiple scripts to run at once, this would be bad. Instead you should write a script in on_boot.d that launches your monitor in a detached session.
