### ISSUE TITLE
UDM Pro upgrade of it's debian system inside unifi-os

### ISSUE THREAD

**Issue by Richigeht** [boostchicken/udm-utilities#163]
Hi, 
This is a bit offtopic, and I might have just missed finding this information bit somewhere, but:

The UDM Pro uses debian old-old-stable currently. And I was wondering, if I either am not seeing the "upgrade here" button basically, or if they really keep it with such an old debian? 
Or should this one have been converted already and I just had the luxury of being unlucky? 

Anyways, if it is "as is" with that old debian, I would wonder if upgrading via cli is just safe or if there is anything else to look at for. 
And then (most likely not tonight though i hope lol) I would maybe just give it a shot. 

Thanks.

**Comment by fabianishere** [comment]
Apparently, UI has repositories for other distributions than stretch (see [here](https://apt.artifacts.ui.com/dists/)). However, I am unsure whether a dist upgrade will be successful. 

A safer alternative might to be enable [Debian Backports](https://backports.debian.org/Instructions/) if you want more recent versions.

**Comment by boostchicken** [comment]
I wouldn't do it.  They removed all upstreams from apt, you could add them back, but why upgrade? Whats your goal?  It would suck to brick the unifi-os container
