### ISSUE TITLE
Custom IPTables Script Guide

### ISSUE THREAD

**Issue by EntropySmoke** [boostchicken/udm-utilities#164]
**Is your feature request related to a problem? Please describe.**
- Built-in UDM NAT filter rules don't cover everything and have some bugs easily remedied by manual IPTables commands executed via SSH, but such commands do not survive a reboot.

**Describe the solution you'd like**
- A guide or an example script for booting IPTables would be great for those who don't know how to write Debian scripts, but know basics of Netfliter IPTables commands. 
- An already-written full script to boot-load custom Netfilter IPTables where we would only need to copy/paste our own IPTables we want applied once UDM boots.

**Describe alternatives you've considered**
- An actual UDM version of Persistent IPTables package (similar to the one for Raspberry Pi) would be really awesome!

**Comment by fabianishere** [comment]
It is not necessary to write complex "Debian" scripts for this use-case. You can just use the [UDM/P Boot Script](https://github.com/boostchicken/udm-utilities/blob/master/on-boot-script/README.md) in this repository to create a simple shell script that runs after boot to insert the necessary IPTables rules.

For instance, once you have installed the boot script, you can create a file `/mnt/data/on_boot.d/05-iptables.sh` with your IPTables rules:
```bash
#!/bin/sh
iptables -t nat -A POSTROUTING -d 213.75.112.0/21 -j MASQUERADE -o eth8
iptables -t nat -A POSTROUTING -d 217.166.0.0/16 -j MASQUERADE -o eth8
```

Alternatively, you could try to see if [iptables-persistent](https://packages.debian.org/nl/stretch/iptables-persistent) works from within the UniFi OS container.
