### ISSUE TITLE
no /mnt/data folder

### ISSUE THREAD

**Issue by twproject** [boostchicken/udm-utilities#165]
**Describe the bug**
On a new UDM with firmware 1.9.3 I don't have /mnt/data folder

**To Reproduce**
ssh to udm pro
unifi-os shell
root@ubnt:/# ls /mnt/data
ls: cannot access '/mnt/data': No such file or directory

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7046065/116379743-9b671080-a813-11eb-8aca-fdf3c339e9e9.png)

**UDM Information**
 - Dream Machine Pro
 - Firmware Version: 1.9.3.3438
 - Controller Version 6.1.71

**Additional context**

**Comment by twproject** [comment]
on my udm pro this is the mnt folder
```
root@ubnt:/mnt# ls -al /mnt
total 9
drwxr-xr-x 1 root root 4096 Apr 28 11:32 .
drwxr-xr-x 1 root root 4096 Apr 28 11:06 ..
drwxr-xr-x 5 root root 1024 Apr 28 04:07 persistent
root@ubnt:/mnt# ls -al /mnt/persistent/
total 21
drwxr-xr-x 5 root root  1024 Apr 28 04:07 .
drwxr-xr-x 1 root root  4096 Apr 28 11:32 ..
drwxr-xr-x 2 root root  1024 Apr 28 04:06 crash-data
-rw-r--r-- 1 root root    11 Apr 28 11:11 date-seed
drwx------ 2 root root 12288 Jan  1  2000 lost+found
-rw-r--r-- 1 root root    36 Apr 28 04:07 setup.id
drwxr-xr-x 2 root root  1024 Apr 28 04:06 ulcmd
root@ubnt:/mnt#
```

**Comment by twproject** [comment]
I solved myself, I create the folder /mnt/data, I rebooted and now the folder contain other directories

Probably you need to update the script or the documentation

Bye

**Comment by jeff-winn** [comment]
The unifi-is shell command gets you into the podman container that’s running the UniFi software. The data folder doesn’t exist in there. Don’t run the command, just SSH into the device and it should be present.

The /mnt/data folder is used for persistent storage whereas the rest of the os seems to run off of a RAM drive and gets wiped on reboot.
