### ISSUE TITLE
1.0.5 on-boot-script install fails on fresh UDM-Pro

### ISSUE THREAD

**Issue by kevinansfield** [boostchicken/udm-utilities#175]
I followed the [on-boot-script install instructions](https://github.com/boostchicken/udm-utilities/blob/master/on-boot-script/README.md) but package install failed and `/mnt/data/on_boot.d` does not exist.

```
root@ubnt:/# dpkg -i udm-boot_1.0.5_all.deb
(Reading database ... 63292 files and directories currently installed.)
Preparing to unpack udm-boot_1.0.5_all.deb ...
rm: can't remove '/mnt/data/on_boot.sh': No such file or directory
dpkg: error processing archive udm-boot_1.0.5_all.deb (--install):
 subprocess new pre-installation script returned error exit status 1
rm: can't remove '/mnt/data/on_boot.sh': No such file or directory
dpkg: error while cleaning up:
 subprocess new post-removal script returned error exit status 1
#-> ubnt-dpkg-cache install
removing /data/dpkg-cache/stretch/packages/udm-boot_1.0.5_all.deb ... done
udm-boot: action=install, package=/data/dpkg-cache/stretch/packages/udm-boot_1.0.5_all.deb mark=manual
<-# ubnt-dpkg-cache install
Errors were encountered while processing:
 udm-boot_1.0.5_all.deb
root@ubnt:/# exit
exit
Error: non zero exit code: 1: OCI runtime error
# cd /mnt/data/on_boot.d
-sh: cd: can't cd to /mnt/data/on_boot.d: No such file or directory
```

**To Reproduce**
1. SSH into UDM-Pro
2. `unifi-os shell`
3. `curl -L https://udm-boot.boostchicken.dev -o udm-boot_1.0.5_all.deb`
4. `dpkg -i udm-boot_1.0.5_all.deb`

**Expected behavior**
Expected no error message and `/mnt/data/on_boot.d` to exist ready for boot scripts to be copied into.

**UDM Information**
 - Variant: Dream Machine Pro
 - Firmware Version: 1.9.3
 - Controller Version: 6.2.25

**Additional context**
This is a new UDM-Pro installed a few days ago and upgraded to latest release, nothing custom outside of basic setup via the controller interface has been done.

**Comment by appark** [comment]
`# unifi-os shell
root@ubnt:/# dpkg -i udm-boot_1.0.4_all.deb
(Reading database ... 67915 files and directories currently installed.)
Preparing to unpack udm-boot_1.0.4_all.deb ...
rm: can't remove '/mnt/data/on_boot.sh': No such file or directory
dpkg: error processing archive udm-boot_1.0.4_all.deb (--install):
 subprocess new pre-installation script returned error exit status 1
rm: can't remove '/mnt/data/on_boot.sh': No such file or directory
dpkg: error while cleaning up:
 subprocess new post-removal script returned error exit status 1
#-> ubnt-dpkg-cache install
removing /data/dpkg-cache/stretch/packages/udm-boot_1.0.5_all.deb ... done
udm-boot: action=install, package=/data/dpkg-cache/stretch/packages/udm-boot_1.0.5_all.deb mark=manual
<-# ubnt-dpkg-cache install
Errors were encountered while processing:
 udm-boot_1.0.4_all.deb
root@ubnt:/# exit
exit
Error: non zero exit code: 1: OCI runtime error`

same here

**Comment by flurie** [comment]
I've been able to get around this by installing v1.0.4 first and then upgrading to v1.0.5.

**Comment by garyd9** [comment]
same issue with UDMP on 1.10.0-11

**Comment by boostchicken** [comment]
This is now fixed.

**Comment by nmusselman** [comment]
![1xg0uv8](https://user-images.githubusercontent.com/50606726/128571007-f41f3787-2dde-461b-9288-9228d61147ca.png)

Please see screenshot

What am I doing wrong?

**Comment by navierb** [comment]
It failed on mine too (I was on 1.0.2) but rebooting it solved the problem.
