### ISSUE TITLE
Unable to set pihole password: 

### ISSUE THREAD

**Issue by JetForMe** [boostchicken/udm-utilities#179]
**Describe the bug**
I followed the steps for setting up P-Hole on my UDM Pro, but was unable to set my the password. I got some errors at the end of launching the container that are similar to the ones you said could be ignored, but they might be more severe:

```
ERRO[0024] CNI network "dns" not found                  
ERRO[0024] Error removing timer for container b422f55187669b82151536b0125248ddd8326b314fe9cfed69e53e712f9b149f healthcheck: unable to get systemd connection to remove healthchecks: dial unix /run/systemd/private: connect: no such file or directory 
Error: error configuring network namespace for container b422f55187669b82151536b0125248ddd8326b314fe9cfed69e53e712f9b149f: CNI network "dns" not found
```

**To Reproduce**

Follow steps for setting up Pi-Hole.

**Screenshots**
![Screen Shot 2021-05-30 at 14 42 42 ](https://user-images.githubusercontent.com/401600/120120911-856fa700-c155-11eb-9f1a-45534f887a22.png)

**UDM Information**
 - UDM Pro
 - Firmware Version: 1.9.3
 - Controller Version 6.2.25

**Additional context**

Here's what I did leading up to this. The UI has changed a lot recently. For example, I couldn't set up a specifically "corporate" network.

```
#  podman run -d --network dns --restart always \
>     --name pihole \
>     -e TZ="America/Los Angeles" \
>     -v "/mnt/data/etc-pihole/:/etc/pihole/" \
>     -v "/mnt/data/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/" \
>     --dns=127.0.0.1 \
>     --dns=1.1.1.1 \
>     --dns=8.8.8.8 \
>     --hostname pi.hole \
>     -e VIRTUAL_HOST="pi.hole" \
>     -e PROXY_LOCATION="pi.hole" \
>     -e ServerIP="192.168.4.2" \
>     -e IPv6="False" \
>     pihole/pihole:latest
Trying to pull docker.io/pihole/pihole:latest...
Getting image source signatures
Copying blob a9b44cf88df1 done
Copying blob 208d49c0abc2 done
Copying blob 113626093de2 done
Copying blob fe9f1fa5a5e0 done
Copying blob 0d3fe530c66a done
Copying blob aceecb32d1c3 done
Copying blob 20749e2af08b done
Copying blob 52ccd329e28b done
Copying config 14ad311e9e done
Writing manifest to image destination
Storing signatures
ERRO[0024] CNI network "dns" not found                  
ERRO[0024] Error removing timer for container b422f55187669b82151536b0125248ddd8326b314fe9cfed69e53e712f9b149f healthcheck: unable to get systemd connection to remove healthchecks: dial unix /run/systemd/private: connect: no such file or directory 
Error: error configuring network namespace for container b422f55187669b82151536b0125248ddd8326b314fe9cfed69e53e712f9b149f: CNI network "dns" not found
# podman exec -it pihole pihole -a -p <redacted>
Error: cannot exec into container that is not running: container state improper
```

**Comment by tjcrandley** [comment]
Did you get an error when you ran the 10-dns.sh script?  I received an error which never set up the dns network interface (I also don't seem to have podman installed either and don't see a step to install it, so I may be a hot mess for other reasons).

**Comment by TobyAnscombe** [comment]
From your screenshot above it looks like you have named the network `pihole` and not `DNS` - worth a check...

**Comment by JetForMe** [comment]
Ah, that might be it.

**Comment by TobyAnscombe** [comment]
@JetForMe - Did that resolve it? if so then can this be closed?

**Comment by JetForMe** [comment]
Been swamped, haven't been able to try it. Close it if you like, I'll reopen if it doesn't work.
