### ISSUE TITLE
unifi-os shell: command not found

### ISSUE THREAD

**Issue by techandbeers** [boostchicken/udm-utilities#18]
**Describe the bug**
unifi-os shell: command not found

**To Reproduce**
1. Enable SSH in UDMP and assign PW
2. SSH in to UDMP using root/PW (Putty)
3. Type "unifi-os shell" (without quotes) and hit enter

**Expected behavior**
Enters shell

**Screenshots**

**UDM Information**
 - Variant: Dream Machine Pro
 - Firmware Version: 1.7.2
 - Controller Version: 5.13.30

**Additional context**
Trying to install pihole, following the steps.

**Comment by boostchicken** [comment]
An alternative is "podman exec -it unifi-os sh".  However, you should absolutely have that command.  /usr/sbin/unifi-os doesn't exist?  It didn't before 1.6.3.  Are you sure you updated the firmware?

**Comment by techandbeers** [comment]
Thanks Boost! The command is working as intended, my mistake!
