### ISSUE TITLE
Podman Error

### ISSUE THREAD

**Issue by Gyarbij** [boostchicken/udm-utilities#183]
**Describe the bug**
Podman not returning values after running update
$podman
/usr/bin/podman: line 1: version: not found
/usr/bin/podman: line 2: oid: not found
/usr/bin/podman: line 3: size: not found

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/49493993/120924519-6c767100-c6d4-11eb-9531-73ad0049e14b.png)

**UDM Information**
Model:       UniFi Dream Machine PRO
Version:     1.9.3.3438
MAC Address: 74:ac:b9:da:72:91

**Additional context**

**Comment by jairbj** [comment]
Same problem here. First time using this script.

**Comment by risdenk** [comment]
I'm pretty sure this is related to #180 and not being able to download the binaries due to LFS quota limitation.

**Comment by boostchicken** [comment]
Fixed!
