### ISSUE TITLE
[Feature Request] Wireguard Kernel Module

### ISSUE THREAD

**Issue by jhoward321** [boostchicken/udm-utilities#185]
With the recent release of a wireguard kernel module for the UDM are there any thoughts about integrating it into these utilities instead of the wireguard-go container? 

I know we should be able to install it manually and use the boot script to run it across reboots, but there might be something else I'm missing. 

It should give much better performance. Either way, [here's the repo](https://github.com/tusc/wireguard-kmod) for anyone interested.

**Comment by boostchicken** [comment]
Def link to it.  I wanna keep this option for those that don't want to run custom kernels / modules.  Maybe update the readme to point to your repo for those who do?

**Comment by boostchicken** [comment]
Also, the wireguard-go container should pick up the kmod if it's there so if you install it and do my route it should still work?

**Comment by jhoward321** [comment]
I'll give that a shot with container, thanks for the info
