### ISSUE TITLE
Error using latest podman binary

### ISSUE THREAD

**Issue by larrifax** [boostchicken/udm-utilities#187]
**Describe the bug**
Hey! I'm trying to install the `podman-update` and have followed the steps in the README. When I run any `podman` command after installation, it fails with the following error message:
```
/usr/bin/podman: line 1: S
                          ▒▒▒6▒-v▒-▒▒@▒@▒▒▒6▒-v▒P▒tdx▒5x▒ux▒uQ▒tdR▒td▒6▒-v▒-vPP/lib64/ld-linux-x86-64.so.2GNU▒▒_▒▒b▒j▒m▒N▒▒U▒#GNUSGoccEX1rb8y3h08cCznKBV/gFs3YzNRkhz6tJFvcWXL/bappRGvnGWZeMo-4e5Vw/3iEvPY7f-Xy7XAsvgN1c▒: not found
/usr/bin/podman: line 1:ELF: not found
/usr/bin/podman: line 2: syntax error: unexpected ")"
```

If I replace `/mnt/data/.cache/podman` with [podman-3.2.0-dev](https://github.com/boostchicken/udm-utilities/blob/master/podman-update/bin/podman-3.2.0-dev) the `podmand` commands work again.

**To Reproduce**
1. Follow the steps in the README to install the podman update
2. Run e.g. `podman version`
3. See error

**UDM Information**
 - Variant: Dream Machine Pro
 - Firmware Version: 1.9.3
 - Controller Version: 6.2.25

**Comment by telnetdoogie** [comment]
You could resolve this locally by changing `PODMAN_VERSION=3.2.0` in `01-podman-update.sh` to `PODMAN_VERSION=3.2.0-dev`.

Longer-term, the binary in the repository needs updated to an aarch64 version

**Comment by boostchicken** [comment]
Is that one not aarch64? I checked it?

**Comment by boostchicken** [comment]
Uploaded fix
