### ISSUE TITLE
multiple nextdns instances

### ISSUE THREAD

**Issue by magic2910** [boostchicken/udm-utilities#19]
Is it possible to start multiple nextdns instances at the same time?
Would like to have one for my home network and one for my guest network (with different policies)

Thank you!

**Comment by boostchicken** [comment]
Yes, you just need to make different CNI networks (20-dns.conflist) for them and repeat the 10-dns.sh for each one.
Make sure you change the name and the IP in the CNI config.  You can leave them on the same VLAN.
