### ISSUE TITLE
Unable to run 01-podman-update.sh

### ISSUE THREAD

**Issue by jakemauer** [boostchicken/udm-utilities#197]
**Describe the bug**
I'm unable to run the 01-podman-update.sh script. My UDM Utilities 1.0.5 install is working fine with my other scripts.

**To Reproduce**
1. Install UDM Utilities 1.0.5
2. Curl then `chmod a+x` the 01-podman-update.sh script
3. Run the script from /mnt/data/on_boot.d directory
4. See error output

**Expected behavior**
Script should complete the Podman updates successfully

**Screenshots**
```
# ./01-podman-update.sh
ln: /usr/libexec/podman/conmon: File exists
ln: /usr/bin/podman: File exists
ln: /usr/bin/runc: File exists
# /usr/bin/podman: line 1: S
                            ���6�-v�-��@�@���6�-v�P�tdx�5x�ux�uQ�tdR�td�6�-v�-vPP/lib64/ld-linux-x86-64.so.2GNU��_��b�j�m�N��U�#GNUSGoccEX1rb8y3h08cCznKBV/gFs3YzNRkhz6tJFvcWXL/bappRGvnGWZeMo-4e5Vw/3iEvPY7f-Xy7XAsvgN1c�: not found
/usr/bin/podman: line 1: ELF: not found
/usr/bin/podman: line 2: syntax error: unexpected ")"
```

**UDM Information**
 - UDM Base
 - Firmware Version 1.9.3
 - Controller Version 6.1.71

**Additional context**
I just updated from UDM Utilities 1.0.4 to 1.0.5 and thought I would add in the "best-practice" scripts that update and configure Podman as I hadn't added those at all.

**Comment by silverl** [comment]
I just hit this too. Did I just destroy my UDM?

```
# ./01-podman-update.sh
# /usr/bin/podman: line 1: S
                            çÐ6Ð-vÐ-üü@ü@¨¨°6°-v°PåtdxÞ5xÞuxÞuQåtdRåtd°6°-v°-vPP/lib64/ld-linux-x86-64.so.2GNUº_ñbÀjmôNùäUï#GNUSGoccEX1rb8y3h08cCznKBV/gFs3YzNRkhz6tJFvcWXL/bappRGvnGWZeMo-4e5Vw/3iEvPY7f-Xy7XAsvgN1c: not found
/usr/bin/podman: line 1:ELF: not found
/usr/bin/podman: line 2: syntax error: unexpected ")"

# ls -l
total 24
-rw-r--r--    1 root     root             0 Jun 29 17:23 ???@@????@8?@.-??@@@@@???????????@??@?????@@?j?j???pp@p@??3???3????p4?pt?pt??????????????6??-v??-v????%???AH??
-rwxr-xr-x    1 root     root           204 Jun 29 14:54 01-multicast-relay.sh
-rwxr-xr-x    1 root     root          1629 Jun 29 17:22 01-podman-update.sh
-rwxr-xr-x    1 root     root           252 Jun 29 17:15 05-container-common.sh
-rwxr-xr-x    1 root     root          1150 Jun 29 17:20 05-install-cni-plugins.sh
-rwxr-xr-x    1 root     root           624 Jun 29 14:49 15-add-root-ssh-key.sh
-rwxr-xr-x    1 root     root            41 Jun 29 15:35 20-start-ntopng
# podman -v
/usr/bin/podman: line 1: S
                          çÐ6Ð-vÐ-üü@ü@¨¨°6°-v°PåtdxÞ5xÞuxÞuQåtdRåtd°6°-v°-vPP/lib64/ld-linux-x86-64.so.2GNUº_ñbÀjmôNùäUï#GNUSGoccEX1rb8y3h08cCznKBV/gFs3YzNRkhz6tJFvcWXL/bappRGvnGWZeMo-4e5Vw/3iEvPY7f-Xy7XAsvgN1c: not found
/usr/bin/podman: line 1:ELF: not found
/usr/bin/podman: line 2: syntax error: unexpected ")"
#
```

**Comment by silverl** [comment]
Studied the `01-podman-update.sh` script and reversed what it did.

```
cd /usr/libexec/podman

# Delete the symbolic link
rm conmon
# Restore the backup file
mv conmon.old conmon

cd /usr/bin
# Delete the symbolic link
rm podman
# Restore the backup file
mv podman.old podman

# Delete the symbolic link
rm runc
# Restore the backup file
mv runc.old runc

# Reverse this change
sed -i 's/driver = "overlay"/driver = ""/' /etc/containers/storage.conf

# Test it out
podman ps
```

**Comment by jdomian** [comment]
Same result here. Going to try @silverl fix to reverse it out as I see all the ",old" files are retained.

**Comment by leeaash** [comment]
The following issue said a solution, using podman 3.2.0-dev instead of 3.2.0
[Error using latest podman binary #187](https://github.com/boostchicken/udm-utilities/issues/187#issuecomment-860076694)

**Comment by jakemauer** [comment]
@leeaash I tried that and received a similar, if not the same error. I didn't log it however.

**Comment by jdomian** [comment]
I switched to use 3.2.0-dev and I don't get the error any more when switching from UDM cli to unifi-os shell

**Comment by jakemauer** [comment]
@jdomian ok I'll give it another shot.

**Comment by jakemauer** [comment]
Well, it hung after spitting out these lines:
```
# ./01-podman-update.sh
# /usr/bin/podman: line 1: version: not found
/usr/bin/podman: line 2: oid: not found
/usr/bin/podman: line 3: size: not found
```

I deleted everything except cni-plugins in .cache and reran then got:
```
ln: /usr/libexec/podman/conmon: File exists
ln: /usr/bin/podman: File exists
ln: /usr/bin/runc: File exists
```

`podman -v` returns 3.2.0-dev so I guess it worked?

**Comment by leeaash** [comment]
Don't forget to modify the path for seccomp.json file in 01-podman-update.sh as I raised issue #188. Then have your fun

**Comment by jakemauer** [comment]
@leeaash The code in your comment is identical to the code in the existing script so I think it may have been fixed.
