### ISSUE TITLE
AdGuardHome and WAN2 Failover

### ISSUE THREAD

**Issue by johnstonjs** [boostchicken/udm-utilities#199]
First, thank you for maintaining this awesome repo so we can take full advantage of the UDM.  Having AdGuardHome on UDM-Pro is just phenomenal.  I'm filling the below bug report to see if anyone has any troubleshooting advice or ideas to resolve, and would be happy to test out potential solutions.

**Describe the bug**
When using the WAN failover feature of the UDM-Pro with WAN1 (Port 9) disconnected and WAN2 (Port 10) active, AdGuardHome is unable to connect to public DNS servers.  Domain names that are already cached will continue to connect, and 10.0.5.3 remains reachable from systems on LAN, but AdGuardHome cannot resolve new DNS requests.

**To Reproduce**
1. Have WAN connections on Port 9 and Port 10
2. Configure UDM-Pro for Failover - [guide here](https://help.ui.com/hc/en-us/articles/360052548713-UniFi-UDM-USG-WAN-Load-Balancing-Configuration-and-Troubleshooting)
3. Open a website such as Github on a connected client.
4. Disconnect WAN1 connection on Port 9.
5. Refresh the open website on the connected client - works
6. Open a different website, such as ui.com, and get a DNS resolution timeout.

**Expected behavior**
With clients still assigned 10.0.5.3 as their DNS server by DHCP, AdGuardHome should be able to use the internet connectivity on WAN2 (Port 10) if WAN1 (Port 9) is unavailable.

**Screenshots**
Can post more if helpful, just ask.

**UDM Information**
 - Variant: Dream Machine Pro
 - Firmware Version: 1.9.3
 - Controller Version 6.2.26

**Additional context**
I installed AdGuardHome on my UDM-Pro in March 2021, before the recent update which includes the cni-plugins script.  If that has any bearing on this, I can try updating to the latest version.  My best guess is that it's a firewall rules issue involving the `AdGuard` network and connectivity to WAN2.

**Comment by boostchicken** [comment]
So I would check to make sure the container is picking up the failover.  Go into the AdGuard container and see if it can talkj to anything after the failover happens.  The net interfaces made by the CNI might need updating

**Comment by johnstonjs** [comment]
Thanks for the quick response.  I got back to the system and found the problem which is not a WAN2 connectivity problem.

For whatever reason, my second ISP is not connecting to the bootstrap DNS servers I had listed for AdGuardHome.  After putting in a couple extra DNS servers for it to use, all is well.

Thanks, and sorry to be a bother.
