### ISSUE TITLE
Smokeping container

### ISSUE THREAD

**Issue by svenvg93** [boostchicken/udm-utilities#20]
I would like to just run Smokeping on the udm.
Any idea if that will be possible.

https://hub.docker.com/r/linuxserver/smokeping

**Comment by boostchicken** [comment]
I don't see why not.  What sort of stuff does is require?  It just looks like it runs a server that pings out.  You could probably just pull the container and mount it with an exposed port.

**Comment by svenvg93** [comment]
@boostchicken it doesn't need much. It just runs Apache, fping and RRD. 
I will give it a try when I have more time to play with it.

**Comment by boostchicken** [comment]
Closing since nobody seems to be really interested in this
