### ISSUE TITLE
Unable to launch containers after updating to 1.10.0

### ISSUE THREAD

**Issue by goose-ws** [boostchicken/udm-utilities#212]
After updating to 1.10,0, I'm unable to launch my "Syncthing" or my "Certbot-DNS" containers. Both fail with the same message:

```
# podman start syncthing
ERRO[0000] Error adding network: failed to create bridge "cni0": could not add "cni0": operation not supported
ERRO[0000] Error while adding pod to CNI network "podman": failed to create bridge "cni0": could not add "cni0": operation not supported
Error: unable to start container "syncthing": error configuring network namespace for container a7ea0c5a053d7d6a96fc8e0b7dde77279fd3b28e532f4d8a9e5e7124cc1f2598: failed to create bridge "cni0": could not add "cni0": operation not supported
# podman start certbot-dns
ERRO[0000] Error adding network: failed to create bridge "cni0": could not add "cni0": operation not supported
ERRO[0000] Error while adding pod to CNI network "podman": failed to create bridge "cni0": could not add "cni0": operation not supported
Error: unable to start container "certbot-dns": error configuring network namespace for container b17ad86cc5604f60be45a86be781640289fdf1adf22014ca7ace5978ef14eaa8: failed to create bridge "cni0": could not add "cni0": operation not supported
#
```

Any ideas on how to fix this?

**Comment by Checksum** [comment]
I've run into the same issue after upgrading to 1.10.0. What's funny is that I'm able to launch adguard on it's isolated VLAN, but can't run any other docker image which tries to create it's own network via the `cni0` bridge.

**Comment by iot-operator** [comment]
What is your podman version? Are you using the podman-update package from here?

**Comment by goose-ws** [comment]
> What is your podman version? Are you using the podman-update package from here?

I was not, but I just set it up. Still no dice, though.

```
# podman version
Version:            1.6.1
RemoteAPI Version:  1
Go Version:         go1.12.10
OS/Arch:            linux/arm64
# ./01-podman-update.sh
# podman version
Version:      3.2.0-dev
API Version:  3.2.0-dev
Go Version:   go1.16.4
Git Commit:   78df4f6fb2e2a404ace69219a50652f4335b7ce1-dirty
Built:        Tue May 25 07:52:19 2021
OS/Arch:      linux/arm64
# ./05-cni.sh
Downloading https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-arm64-v0.9.1.tgz.sha256
Downloading https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-arm64-v0.9.1.tgz
Pouring /mnt/data/.cache/cni-plugins/cni-plugins-linux-arm64-v0.9.1.tgz
# podman start syncthing
ERRO[0000] Error adding network: failed to create bridge "cni0": could not add "cni0": operation not supported
ERRO[0000] Error while adding pod to CNI network "podman": failed to create bridge "cni0": could not add "cni0": operation not supported
ERRO[0000] error loading cached network config: network "podman" not found in CNI cache
WARN[0000] falling back to loading from existing plugins on disk
Error: unable to start container "a7ea0c5a053d7d6a96fc8e0b7dde77279fd3b28e532f4d8a9e5e7124cc1f2598": error configuring network namespace for container a7ea0c5a053d7d6a96fc8e0b7dde77279fd3b28e532f4d8a9e5e7124cc1f2598: failed to create bridge "cni0": could not add "cni0": operation not supported
#
```

**Comment by Checksum** [comment]
No luck with updated `podman` here either:

```
ERRO[0000] Error adding network: failed to create bridge "cni0": could not add "cni0": operation not supported
ERRO[0000] Error while adding pod to CNI network "podman": failed to create bridge "cni0": could not add "cni0": operation not supported
INFO[0000] Got pod network &{Name:bitwarden Namespace:bitwarden ID:1c019ffe093c918d78eae4ad189c7d487f8aa328646c18944fbac3430797b2bc NetNS:/run/netns/cni-0cd36809-555e-fd72-ebdf-162e518f11e0 Networks:[{Name:podman Ifname:eth0}] RuntimeConfig:map[podman:{IP: MAC: PortMappings:[{HostPort:9443 ContainerPort:80 Protocol:tcp HostIP:} {HostPort:3012 ContainerPort:3012 Protocol:tcp HostIP:}] Bandwidth:<nil> IpRanges:[]}] Aliases:map[]}
ERRO[0000] error loading cached network config: network "podman" not found in CNI cache
```

**Comment by cb88** [comment]
Does your conflist look like so? Note the mac address must be a known one I left the bits in there that identify mine as a ubiquiti device in case you want to base one off that. Below is working on 1.10.0 with pihole.

```
# cat /mnt/data/podman/cni/20-dns.conflist
{
  "cniVersion": "0.4.0",
  "name": "test",
  "plugins": [
    {
      "type": "macvlan",
      "mode": "bridge",
      "master": "br5",
      "mac": "00:15:6D:xx:xx:xx",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.80.2/24",
            "gateway": "192.168.80.1"
          }
        ],
        "routes": [
          {"dst": "0.0.0.0/0"}
        ]
      }
    }
  ]
```

**Comment by Checksum** [comment]
Looked into this a bit more. Looks like the network interface `cni0` isn't actually available. I created a bridge interface with that name and it worked!

```
ip link add cni0 type bridge
```

I don't know how that went missing after the upgrade, or if it will survive a reboot, but at least it works for now.

**Comment by goose-ws** [comment]
> Does your conflist look like so? Note the mac address must be a known one I left the bits in there that identify mine as a ubiquiti device in case you want to base one off that. Below is working on 1.10.0 with pihole.
> 
> ```
> # cat /mnt/data/podman/cni/20-dns.conflist
> {
>   "cniVersion": "0.4.0",
>   "name": "test",
>   "plugins": [
>     {
>       "type": "macvlan",
>       "mode": "bridge",
>       "master": "br5",
>       "mac": "00:15:6D:xx:xx:xx",
>       "ipam": {
>         "type": "static",
>         "addresses": [
>           {
>             "address": "192.168.80.2/24",
>             "gateway": "192.168.80.1"
>           }
>         ],
>         "routes": [
>           {"dst": "0.0.0.0/0"}
>         ]
>       }
>     }
>   ]
> ```

I do not have a dns.conflist in my /mnt/data/podman/cni/ path.

> Looked into this a bit more. Looks like the network interface `cni0` isn't actually available. I created a bridge interface with that name and it worked!
> 
> ```
> ip link add cni0 type bridge
> ```
> 
> I don't know how that went missing after the upgrade, or if it will survive a reboot, but at least it works for now.

This seems to have fixed it for me. I tested a reboot and it did not survive, so I added the following `03-cni-bridge.sh`  in my `/mnt/data/on_boot.d/`:

```sh
#!/bin/sh

# Does the cni0 bridge exist?
ip link show cni0 > /dev/null 2>&1
exitCode="${?}"

if [[ "${exitCode}" -ne "0" ]]; then
    ip link add cni0 type bridge
fi
```

**Comment by superm1** [comment]
> ip link add cni0 type bridge

This seems to help me too.  I got hit by this when I turned on UID (I guess it forced the upgrade to 1.10.4 so I got hit by this too).

**Comment by superm1** [comment]
I was able to solve it by re-running `05-install-cni-plugins.sh` to grab a newer version of the CNI plugins.  On reboot everything came back up properly.

**Comment by boostchicken** [comment]
Make sure you grab the latest cni plugins, also, make sure you have specified a network of some sort "--network bridge"
