### ISSUE TITLE
Help with setting DHCPv6 duid on WAN interface

### ISSUE THREAD

**Issue by dvcrn** [boostchicken/udm-utilities#215]
Hi! I got myself an UDM to upgrade from my USG and am trying to convert my configuration over. I am still wrapping myself around everything, but I need help with configuring IPv6 DHCPv6 on the wan interface:

```
{
  "interfaces": {
    "ethernet": {
      "eth0": {
        "dhcpv6-pd": {
          "duid": "foobar123",
        }
      }
    }
  }
}
```

There is `/etc/systemd/networkd.conf` which I updated to my needed duid, but I don't think the UDM is even using this because networkd is off (`systemctl status sytemd-networkd`). 

How can I configure this? I can't even find information on the DHCPv6 client it's using, it's logs or how to mess with it

**Comment by dvcrn** [comment]
I ended up getting it working

`odhcp6c` is taking a `-c` arg that sets DUID but it's getting launched by `ubios-udapi-server`, so there is no way to change the startup without disassembling ubios-udapi-server

Found an easier solution: Replace `odhcp6c` with a custom script that calls the original and injects the `-c` arg.

**Comment by giovannirco** [comment]
hey @dvcrn can you open a PR with some examples on how you accomplished this? I am struggling to get this done on my homelab and I would appreciate some guidance on this one if you can.

**Comment by dvcrn** [comment]
> hey @dvcrn can you open a PR with some examples on how you accomplished this? I am struggling to get this done on my homelab and I would appreciate some guidance on this one if you can.

I actually wrote a blog post about this :) https://david.coffee/teaching-my-unifi-udm-how-to-ipv6/

Let me know if anything is still unclear

**Comment by giovannirco** [comment]
amazing!!!! Very well documented, Now I understand what you did and now I understand ipv6 a bit better.
quoting your own words: I just assumed IPv6 was identical to IPv4, just bigger, but boy was I wrong

Thank man! I hope you have a good night and an amazing week :D

**Comment by gavinzhou** [comment]
@dvcrn 

I tryed
ISP > UDM-SE gets ipv6, but I found that starting odhcp6c with the same command doesn't get ipv6.
I got the DUID through wireshark and I can't get the ipv6 address by executing the command, is there any other way to try?
