### ISSUE TITLE
HOW TO Backup your UDM backup *.unf files to another server like Unraid NAS

### ISSUE THREAD

**Issue by rcmpayne** [boostchicken/udm-utilities#22]
1. Create this script on unraid (can be adopted on any bash shell)
2. Edit the values as needed in the script as well as the prerequs
3. Set the script to run daily

This will overcome a bunch of issues like unraid not having some of the command line options (SSHPASS) as well as rsa keys are wiped on reboot of UDM-Pro

Script:
https://pastebin.com/P3JStizH

**Comment by boostchicken** [comment]
@rcmpayne do you want to move this to Wiki?

**Comment by boostchicken** [comment]
Moved to wiki
