### ISSUE TITLE
Adguardhome on UDM installation issues

### ISSUE THREAD

**Issue by drentjess** [boostchicken/udm-utilities#225]
**Describe the bug**
Trying to install Adguardhome on my UDM. After going through the readme file and executing the following code, I get an error and can't continue. I'm not so familiar with setting up these kinds of things so I would appreciate the help. Bit out of my league, but I want to run Adguard Home from my UDM so I have to. 

```
podman run -d --network dns --restart always  \
    --name adguardhome \
    -v "/mnt/data/AdguardHome-Confdir/:/opt/adguardhome/conf/" \
    -v "/mnt/data/AdguardHome-Workdir/:/opt/adguardhome/work/" \
    --dns=127.0.0.1 --dns=1.1.1.1 \
    --hostname adguardhome \
    adguard/adguardhome:latest
```

Error: unable to find network configuration for dns: network not found

**20-dns.conflist**
```
{
  "cniVersion": "0.4.0",
  "name": "dns",
  "plugins": [
    {
      "type": "macvlan",
      "mode": "bridge",
      "master": "br5",
      "mac": "<generated mac address>",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.2.0/24",
            "gateway": "192.168.1.1"
          }
        ],
        "routes": [
          {"dst": "0.0.0.0/0"}
        ]
      }
    }
  ]
}
```

**10-dns.sh**
```
#configuration variables:
VLAN=5
IPV4_IP="192.168.2.0"
IPV4_GW="192.168.1.1/24"

IPV6_IP=""
IPV6_GW=""

FORCED_INTFC="br5"
CONTAINER=adguardhome
```

**Network settings for adguard home network in UDM** 
Subnet: 192.168.2.0/24
VLAN ID: 5
DHCP Mode: None
Other settings: emtpy

**Please help**
Please help me, I would really appreciate it. Thanks in advance.

**Comment by HideTheMonkey** [comment]
Is the MAC in 20-dns.conflist actually "**<generated mac address>**" or did you just use that for posting here?

I commented on a similar issue in https://github.com/boostchicken/udm-utilities/issues/112.  I believe you MUST use a MAC address from a registered company in order for this to work.  Try https://macaddress.io/mac-address-generator and check the "Registered only" option.  Good luck!

**Comment by drentjess** [comment]
I fixed it already, had the wrong IP's configured. Thanks though!
