### ISSUE TITLE
Adguard Home docker URL changed

### ISSUE THREAD

**Issue by rodalpho** [boostchicken/udm-utilities#23]
As of the latest version there's no need to specify arm64 etc, you can just use "adguard/adguardhome:latest". The old link still works for now, unknown if it will continue to work. Reference here:

https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.103.1

(Note, 0.103.3 is the latest version including hotfixes).

**Comment by SturdyErde** [comment]
[Pull request](https://github.com/boostchicken/udm-utilities/pull/25) submitted for the AdGuard Home readme.md

**Comment by boostchicken** [comment]
Merged, thanks!
