### ISSUE TITLE
Large timeout issues causing DNS fallback

### ISSUE THREAD

**Issue by 1activegeek** [boostchicken/udm-utilities#235]
**Describe the bug**
It appears I have some sort of timeout or delay in lookup/response as of a day or 2 ago. I'm not certain this is specifically an issue with your implementation, but more hoping I'm not the only one and there may be some troubleshooting you can point to identifying this issue as being the UDM, the PiHole, or something else.

**To Reproduce**
Not manually reproducable at the moment. Currently it affected me yesterday starting around 230AM, I turned off some HC.io checks, restarted some devices, and later that afternoon, I noticed that resolution was happening fine again and was going to pihole. This morning, woke to a flurry of HC.io checks failing/passing - leading me to identify that my DNS queries were being delayed again when going to pihole, so it was falling back to the UDM itself resolving (Aka going direct out). I can also tell because my local resolution of hosts breaks as well that were configured in pihole.

**Expected behavior**
DNS queries to be resolved properly, and be filtered through pihole.

**UDM Information**
 - UDM-Pro
 - Firmware: 1.10.0.3686
 - Controller Version: 6.2.26

**Additional context**
Output from CLI in nslookup, dig, and ping. This is all after clearing local cache on machine. Additionally if I switch my DNS MANUALLY to 10.0.5.3 (vs DHCP DNS of 10.0.5.3, 10.0.10.1, 1.1.1.1, 8.8.8.8) - it will ping.
```
user@computer Downloads % nslookup mydomain.com
Server:		10.0.5.3
Address:	10.0.5.3#53

Name:	mydomain.com
Address: 10.0.10.22

user@computer Downloads % dig @10.0.5.3 mydomain.com

; <<>> DiG 9.10.6 <<>> @10.0.5.3 mydomain.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40356
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mydomain.com.		IN	A

;; ANSWER SECTION:
mydomain.com.	2	IN	A	10.0.10.22

;; Query time: 0 msec
;; SERVER: 10.0.5.3#53(10.0.5.3)
;; WHEN: Fri Aug 27 09:40:04 EDT 2021
;; MSG SIZE  rcvd: 61

user@computer Downloads % ping mydomain.com
PING mydomain.com (104.21.7.253): 56 data bytes
64 bytes from 104.21.7.253: icmp_seq=0 ttl=49 time=26.942 ms
64 bytes from 104.21.7.253: icmp_seq=1 ttl=49 time=26.753 ms
```

**Comment by 1activegeek** [comment]
im waiting to let my HC.io checks startup again and run for at least 24 hours before i'll confirm - but it would appear that it has now settled back down, and seems to have been running well for almost a day again - will report back if it is in fact ok again or if there is something that kicks up after running for awhile again

**Comment by boostchicken** [comment]
Assuming this is fixed, re open if it isnt.

**Comment by 1activegeek** [comment]
Yup, sorry never came back and closed it out. All good!
