### ISSUE TITLE
Error installing homebridge

### ISSUE THREAD

**Issue by martinschki** [boostchicken/udm-utilities#237]
Hello,

I'm getting the following errors when installing homebridge on my UDM Pro. What am I missing please?
Thank you
....
Copying blob d0536b6ae09d done
Copying blob d043f03d482b done
Copying config 6610603e9a done
Writing manifest to image destination
Storing signatures
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
WARNING: The same type, major and minor should not be used for multiple devices.
ERRO[0072] CNI network "homebridge" not found
Error: error configuring network namespace for container 4ba2016f69efdb3da6c60ed0232319b9034bee7742dbccb9b533f549ec579417: CNI network "homebridge" not found

**Comment by sundar2012** [comment]
did you confirm all the supporting files are where they need to be with the right permissions?

try running all this
`curl -L https://raw.githubusercontent.com/boostchicken/udm-utilities/master/container-common/on_boot.d/05-container-common.sh -o /mnt/data/on_boot.d/05-container-common.sh;
# Set execute permission
chmod a+x /mnt/data/on_boot.d/05-container-common.sh;

# Apply container-common settings
/mnt/data/on_boot.d/05-container-common.sh;

# Download 05-container-common.sh from GitHub
curl -L https://raw.githubusercontent.com/boostchicken/udm-utilities/master/cni-plugins/05-install-cni-plugins.sh -o /mnt/data/on_boot.d/05-install-cni-plugins.sh;
# Set execute permission
chmod a+x /mnt/data/on_boot.d/05-install-cni-plugins.sh;
# install
/mnt/data/on_boot.d/05-install-cni-plugins.sh;


curl -L https://raw.githubusercontent.com/boostchicken/udm-utilities/master/podman-update/01-podman-update.sh -o /mnt/data/on_boot.d/01-podman-update.sh;
# Set execute permission
chmod a+x /mnt/data/on_boot.d/01-podman-update.sh;


curl -L https://raw.githubusercontent.com/boostchicken/udm-utilities/master/homebridge/on_boot.d/25-homebridge.sh -o /mnt/data/on_boot.d/25-homebridge.sh;
# Set execute permission
chmod a+x /mnt/data/on_boot.d/25-homebridge.sh;

curl -L https://raw.githubusercontent.com/boostchicken/udm-utilities/master/homebridge/cni/90-homebridge.conflist -o /mnt/data/podman/cni/90-homebridge.conflist
# Set execute permission
chmod a+x /mnt/data/podman/cni/90-homebridge.conflist`

**Comment by martinschki** [comment]
Thank you!
For the weirdest reason when copy/pasting the 90-homebridge.conflist content to the file into the console using vim as described in the readme of homebridge, it swallows the first line and some characters from the second line
I can reproduce that...
go figure...

working now - thank you!

**Comment by martinschki** [comment]
Well, I do have another question. Actually two:

- when I change a firewall rule, homebridge stops working

- when I reboot UDM Pro, homebridge is not running

anyone please??

**Comment by sundar2012** [comment]
I have the same issue with homebridge and the firewall.  I have to reboot the whole damn thing.  However, when I reboot, homebridge does run.  I would rm your 25-homebridge.sh file and then repush it directly using the script above.

**Comment by martinschki** [comment]
Is this firewall thing already reported or should I open a new one?

**Comment by sundar2012** [comment]
Maybe close this and open a new one?
