### ISSUE TITLE
Running Pihole with DoTe rather than Cloudflared

### ISSUE THREAD

**Issue by chrisstaite** [boostchicken/udm-utilities#244]
I have been using the pihole with cloudflared solution for a while, but cloudflared seems flakey and I have to reboot about once a week.  I was previously using my own DNS-over-TLS solution that I wrote for my EdgeMAX Lite-3, so I re-compiled it for ARM64 and popped it in the container.  I've just updated my documentation as to how to do this, but didn't know if you wanted to add it as a link to your documentation too.

Project is at: https://github.com/chrisstaite/DoTe/.

**Comment by na** [comment]
I'm trying to get DoTe working on my UDMP with Pihole.  Should it work with just the 127.0.0.1#5053 upstream server set in Pihole?  For me, I get resolution issues unless I also set another server:  
![image](https://user-images.githubusercontent.com/1600/148659251-08ed6cc3-29b4-48a7-bc07-1188b42e548d.png)

Is there a good way to check that it is working? I've tired both the custom_pihole_dote.sh and the run command from https://github.com/chrisstaite/DoTe/

**Comment by chrisstaite** [comment]
Certainly just works here. Are you sure you're not running another pihole image that you're connecting to rather than the DoTe instance? You shouldn't have to set the forwarder as it should be set as part of the start up.

**Comment by na** [comment]
Yeah, I'm pretty sure I'm connecting to the DoTe instance.  Only 1 pihole container is running:  

![image](https://user-images.githubusercontent.com/1600/148661145-cda80a65-6a6f-4244-8978-5d6521a49ce1.png)

Does DoTe do any logging that I can check?

**Comment by chrisstaite** [comment]
It logs to syslog but I'm not sure where that is in the container.

**Comment by shaft8472** [comment]
> I'm trying to get DoTe working on my UDMP with Pihole. Should it work with just the 127.0.0.1#5053 upstream server set in Pihole? For me, I get resolution issues unless I also set another server: ![image](https://user-images.githubusercontent.com/1600/148659251-08ed6cc3-29b4-48a7-bc07-1188b42e548d.png)
> 
> Is there a good way to check that it is working? I've tired both the custom_pihole_dote.sh and the run command from https://github.com/chrisstaite/DoTe/

Did you solve this issue? I'm running into the same problem.
