### ISSUE TITLE
Is UDM Utilities Suricata script still applicable?

### ISSUE THREAD

**Issue by EntropySmoke** [boostchicken/udm-utilities#247]
Once again Ubiquiti is using out-of-data Suricata 5.X. Would the obsolete Suricata script (https://github.com/boostchicken/udm-utilities/blob/master/suricata/README.md) be able to update both - Suricata rules and the Suricata APP itself to 6.X.X?t

**Comment by boostchicken** [comment]
Docker = podman.

If you look at my scripts you will see how it kills suricata.  @GhostlyCrowd why dont you submit a PR and I can revive it.
