### ISSUE TITLE
unifi-os shell not available on UDM Pro SE version 2.2.12

### ISSUE THREAD

**Issue by craigueh** [boostchicken/udm-utilities#257]
When I try to run # unifi-os shell I get the following error -bash: unifi-os: command not found
This is on a new UDM Pro SE with version 2.2.12 of Unifi OS from what I can see.

Is there any workaround or am I doing something wrong?

**Comment by FlorentCoppint** [comment]
There is no containers, you already are in unifi-os

**Comment by craigueh** [comment]
Ok, so presumably I just skip that step and move on?

When I try  dpkg -i udm-boot_1.0.5_all.deb
I get the following error:

Selecting previously unselected package udm-boot.
(Reading database ... 73332 files and directories currently installed.)
Preparing to unpack udm-boot_1.0.5_all.deb ...
/var/lib/dpkg/tmp.ci/preinst: 19: /var/lib/dpkg/tmp.ci/preinst: /sbin/ssh-proxy: not found
dpkg: error processing archive udm-boot_1.0.5_all.deb (--install):
 subprocess new pre-installation script returned error exit status 127
/var/lib/dpkg/tmp.ci/postrm: 24: /var/lib/dpkg/tmp.ci/postrm: /sbin/ssh-proxy: not found
dpkg: error while cleaning up:
 subprocess new post-removal script returned error exit status 127
Errors were encountered while processing:
 udm-boot_1.0.5_all.deb

Not sure where to go from here or if the steps are differnt for a UDM Pro SE?

**Comment by traek** [comment]
Getting the same issue. Tried in the firmware that mine shipped with (2.2.5) as well as the latest you did (2.2.12).

**Comment by boostchicken** [comment]
There is no support for this on the SE device, there is another repo for it since it uses systemd

**Comment by traek** [comment]
Yes, but which repo?

**Comment by mazzy89** [comment]
I was wondering too whether any repo w/ existing systemd services would be already available. I could find only this https://github.com/ntkme/unifi-systemd-units so I guess you mean this repo.

**Comment by zms** [comment]
I think he meant [this repo](https://github.com/unifi-utilities/unifios-utilities/tree/main/on-boot-script-2.x).
