### ISSUE TITLE
External Access to HAProxy (or any port)

### ISSUE THREAD

**Issue by tanishq-dubey** [boostchicken/udm-utilities#291]
**Describe the bug**
I am trying to access services running on my UDM Pro (powered by udm-utilities). One of these is HAProxy. I have my website hosted on a set of machine at home and want to load balance between them, so running HAProxy on the UDM seems to make the most sense. When routed through the UDM from a machine on my local network, things work just fine, but when accessing over the public internet. there is no access at all. I've done port forwarding, checked IP Tables, but this seems to be a firewall issue, since I can't even see packets sent over `tcpdump

To do a simple test, I have this setup:

On the UDM Pro:

```
nc.traditional -l -p 12345
```
**To Reproduce**
1. On the UDM run `nc.traditional -l -p 12345`. This will begin listening for data on port 12345
2. Set up port-forwarding from the Unifi web console. in this case: "Forward traffic on port 12345 -> 192.168.1.1:12345"
![image](https://user-images.githubusercontent.com/3333201/145908583-25cbd487-257a-46cd-88d8-aef302f64f2b.png)
3. On a machine that is on the network, try a telnet, this will work: 
![image](https://user-images.githubusercontent.com/3333201/145908664-82352e29-e037-4bfa-9c20-a4b73b8f2b3a.png)
4. Try from a machine that is not on the network and the port cannot be reached
![image](https://user-images.githubusercontent.com/3333201/145908801-89ba91dc-dd62-4a40-9788-f462dcdf80f6.png)

**Expected behavior**
With the port forwarding, I would expect this to just work, and it does work when I target a machine that is not the UDM, so I am wondering if there is something I need to disable. My intuition is that there is some firewall/setting I am missing.

**UDM Information**
 - Dream Machine Pro
 - Firmware Version: 1.10.4
 - Controller Version 6.2.26

**Comment by tanishq-dubey** [comment]
Resolved by creating a `wan_local` rule:

![image](https://user-images.githubusercontent.com/3333201/146284196-4d87f16e-aaac-4448-9ab1-023b0e2cbc43.png)


![image](https://user-images.githubusercontent.com/3333201/146284219-85528b84-4932-496f-b552-7317a2410997.png)


![image](https://user-images.githubusercontent.com/3333201/146284240-e393f016-6191-4f10-9f5e-c9caa528ce1d.png)

**Comment by boostchicken** [comment]
This was working a while ago.  I am not sure if they made another change,  However, I do not think the group would be Internet Local, you are not using a loopback to get to your WAN port.

**Comment by boostchicken** [comment]
and wow I just proved how big of an idiot I am, I should read more next time. Glad you fixed it!
