### ISSUE TITLE
Unable to use install-cni-pluggins.sh

### ISSUE THREAD

**Issue by i-am-pierre** [boostchicken/udm-utilities#3]
Unable to install cni using your script.
After copying the script to /mnt/data and make it executable using chmod u+x on it, the script fail.

```
# chmod u+x /mnt/data/install-cni-plugins.sh 
# ./install-cni-plugins.sh 
-sh: ./install-cni-plugins.sh: not found
```

**Comment by sfhoo** [comment]
Use sh install-con-plug-ins.sh

**Comment by i-am-pierre** [comment]
Yah, I ended up typing all command from the shell script

**Comment by boostchicken** [comment]
@i-am-pierre I fixed this, there was a bad shebang on that scripts
