### ISSUE TITLE
Pihole, conditional forwarding not working.

### ISSUE THREAD

**Issue by jinie** [boostchicken/udm-utilities#30]
Thanks for this excellent project. It adds a few missing parts to the UDM 👍 

I’ve setup pihole on VLAN 100 (172.16.100.0/24), and I have dns lookups working from the client computers. Pihole also resolves addresses using cloudflare, but I cannot seem to get conditional forwarding working.

I have 6 different VLANs, and no matter which address I try to do nslookup to from the pihole container I get timeouts. Lookups to an external (DMZ) pihole works from the container.

I’ve fiddled around with firewall rules all day, and even if I allow all traffic to/from the dns vlan it still isn’t allowed to connect. No DNS appears to be listening on the gateway IP either (172.160.100.1).

I can resolve just fine from one vlan using the gateway address on another vlan, just not from the pihole container.

Am I being locked out by dnsmasq config ?

**Comment by Allram** [comment]
Same problem here with UDMP.
4 VLAN and conditional forwarding is not working.

**Comment by boostchicken** [comment]
Did you check the latest 10-dns.sh?   It has the fix.

**Comment by jtychu** [comment]
I gave the latest a try and it appears to be working. Thanks!
