### ISSUE TITLE
Full Installation wiki page

### ISSUE THREAD

**Issue by mbnn** [boostchicken/udm-utilities#33]
Hello,

Love your project however, Im still not able to get this to work on my UDM Pro.
How does this all begin? What are the first steps to get the basics going and then add nextdns?
Do you have to download the entire git first and copy it to the UDM Pro or (and if so, to which directory)? Does not say this anywhere.

Manually copying the files into the right directories does not seem to work for me.
For example; I first went through the https://github.com/boostchicken/udm-utilities/tree/master/on-boot-script << that manual, all steps completed. Then I went to the nextdns manual, but whenever I do: 

```
# ./10-dns.sh 
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
podman-dns: Container nextdns not found, make sure you set the proper name, if you have you can ignore this error
```

Why is this happening? the readme does not say anything about having to unifi-os shell or not before doing all those steps?

PS. Also a guide on how to uninstall everything would be cool 😀

**Comment by nschemel** [comment]
Hi,

the 'podman-dns' error suggests, that you didn't create the nextdns container before.

The script '10-dns.sh' tries to start the container, but fails if it hasn't been created yet.

For creating the container you have to run the podman command from the nextdns readme under step 6. After that the error shouldn't come up anymore when running the script.

It's a minor annoyance in the readme, because step 3 suggests to run the script, but the container is created afterwards. As far as I know that shouldn't impact the result.

I'm planning to make a suggestion for a script change on the weekend, so that the error doesn't occur on the first run.

**Comment by boostchicken** [comment]
Yeah, that is not a problem.  Just create the container afterwards.  I might remove that error as it seems to be confusing people.

**Comment by mbnn** [comment]
One last question:

How does this all begin? What are the first steps to get the basics going and then add nextdns?
Do you have to download the entire git first and copy it to the UDM Pro or (and if so, to which directory)? Does not say this anywhere.

**Comment by boostchicken** [comment]
@mbnn no, you just need to install the on-boot package and then you can scp the example files, copy and paste using vi, whatever you preferred method it.  For installing the on boot, just follow the instructions to download the .deb package and install it.

**Comment by boostchicken** [comment]
Also, what do you want an installation page of?  All installation instructions are in each folders README.md.

**Comment by mbnn** [comment]
Yes but those readme files do not include anything about how to copy files and from which directories (only the destination) :) And my basic question therefor was if you need to copy the entire git dir first or something :)

**Comment by mbnn** [comment]
And when you have to copy those files to the mnt/data dir,  is that under unifi-os shell or in the normal ssh admin shell?

**Comment by SturdyErde** [comment]
I'll try to contribute to documentation. Might be helpful because, being new-ish to both Linux and GitHub, steps that seem obvious to a seasoned user don't always seem obvious to me. For example, learning that I had to make the .sh file executable by using `chmod +x ./10-dns.sh`.

**Comment by boostchicken** [comment]
@mbnn sorry, the instructions are written assuming you have a basic understanding of Unix Sys Admin experience.  Thanks @SturdyErde  for volunteering to write some more documentation, I simply don't have time at the moment.  I will try to make a youtube of doing it as someone suggested.  I am going to close this issue.  Feel free to contribute to the wiki or send PR's to the README.md files if you feel the documentation could be better.
