### ISSUE TITLE
Zoneminder Container

### ISSUE THREAD

**Issue by DaCapone1986** [boostchicken/udm-utilities#38]
Hi,

Can you take a look at Zoneminder please, i would realy love to see this on my udm pro
I like unifi protect but it is useless for me, becouse i realy need the ONVIF support

Best regards

**Comment by boostchicken** [comment]
If you are doing protect, you should have a UDMP for sure.  How is it using 16gb of ram also?  Thats like the whole device?

**Comment by boostchicken** [comment]
On further review, I won't do this.  This whole product is hot trash, requiring SQL, Perl, PHP, Apache, custom binaries to run one application?  You are asking for a vulnerability and having your whole UDM owned.  I would run this on another appliance.  If you are so driven, build a docker container for a linux distribution of your choosing targeting the arm64 platform as described in their documentation.

Their docker image is quite terrible as well, weighing in at 400+ megs.  Might want to clean that up.
