### ISSUE TITLE
Wireguard Problem

### ISSUE THREAD

**Issue by cstrassmair** [boostchicken/udm-utilities#39]
Hello,

can anyone tell me what iam doing wrong?

I am trying to get wireguard go to work.
I want to connect via VPN Provider which offers a connection via Wireguard

Output

Warning: `/etc/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
RTNETLINK answers: Not supported
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
[#] wireguard-go wg0
WARNING WARNING WARNING WARNING WARNING WARNING WARNING
W                                                     G
W   You are running this software on a Linux kernel,  G
W   which is probably unnecessary and misguided. This G
W   is because the Linux kernel has built-in first    G
W   class support for WireGuard, and this support is  G
W   much more refined than this slower userspace      G
W   implementation. For more information on           G
W   installing the kernel module, please visit:       G
W           https://www.wireguard.com/install         G
W                                                     G
WARNING WARNING WARNING WARNING WARNING WARNING WARNING
INFO: (wg0) 2020/08/24 13:36:08 Starting wireguard-go version 0.0.20200320
[#] wg setconf wg0 /dev/fd/63
INFO: (wg0) 2020/08/24 13:36:08 Starting wireguard-go version 0.0.20200320
INFO: (wg0) 2020/08/24 13:36:08 Interface set up
INFO: (wg0) 2020/08/24 13:36:08 Device started
INFO: (wg0) 2020/08/24 13:36:08 UAPI listener started
[#] ip -4 address add 10.100.2.2/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] ip -4 route add 192.168.1.0/24 dev wg0
RTNETLINK answers: File exists
[#] resolvconf -d wg0 -f
[#] ip link delete dev wg0
INFO: (wg0) 2020/08/24 13:36:09 Interface set down
ERROR: (wg0) 2020/08/24 13:36:09 Failed to read packet from TUN device: read : file descriptor in bad state
INFO: (wg0) 2020/08/24 13:36:09 Device closing
INFO: (wg0) 2020/08/24 13:36:09 Shutting down
Error: non zero exit code: 2: OCI runtime error

Any Idea whats wrong?

Thanks
Christoph

**Comment by boostchicken** [comment]
Please post your configs, it would appear you have issues with what routes you are allowing.

[#] ip -4 route add 192.168.1.0/24 dev wg0
RTNETLINK answers: File exists

**Comment by cstrassmair** [comment]
Hello,

its nothing special.
I think thats the right way.

i changed it just to test to 192.168.1.10/32 thats one IP of a Windows Client

Now its doing without an error

INFO: (wg0) 2020/08/26 12:46:58 Starting wireguard-go version 0.0.20200320
[#] wg setconf wg0 /dev/fd/63
INFO: (wg0) 2020/08/26 12:46:58 Starting wireguard-go version 0.0.20200320
INFO: (wg0) 2020/08/26 12:46:58 Interface set up
INFO: (wg0) 2020/08/26 12:46:58 Device started
INFO: (wg0) 2020/08/26 12:46:58 UAPI listener started
[#] ip -4 address add 10.100.2.2/32 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] ip -4 route add 192.168.1.10/32 dev wg0

But 
podman exec -it wireguard wg

Shows nothing

**Comment by boostchicken** [comment]
Can you post the wg0.conf (with your secrets redacted), also an ifconfig from the UDM?

**Comment by 11ib** [comment]
Hi all, getting a similar error.

`podman exec -it wireguard wg` shows nothing

`# podman exec -it wireguard wg-quick up wg0
Warning: '/etc/wireguard/wg0.conf' is world accessible
[#] ip link add wg0 type wireguard
RTNETLINK answers: Not supported
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
[#] wireguard-go wg0
`

(warning block shown above about running in the Linux kernel)

then
`
INFO: (wg0) 2020/11/19 07:42:45 Starting wireguard-go version 0.0.20200320
[#] wg setconf wg0 /dev/fd/63
INFO: (wg0) 2020/11/19 07:42:45 Starting wireguard-go version 0.0.20200320
INFO: (wg0) 2020/11/19 07:42:45 Interface set up
INFO: (wg0) 2020/11/19 07:42:45 Device started
INFO: (wg0) 2020/11/19 07:42:45 UAPI listener started
[#] ip -4 address add 192.168.129.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
`

screenshot of wg0.conf below, my UDM is on the 192.168.128.0/24 subnet

![Screen Shot 2020-11-18 at 11 47 37 PM](https://user-images.githubusercontent.com/10055660/99636573-75357d00-29f8-11eb-9231-fcb809ed211f.png)

**Comment by boostchicken** [comment]
Everything looks like it happened fine there?  What are the errors?  They are directly related to your POstUp PostDown scripts whatever they are
