### ISSUE TITLE
Use conditional Forwarding on the PiHole, and other DNS settings

### ISSUE THREAD

**Issue by i-am-pierre** [boostchicken/udm-utilities#4]
Any change you would know how to have the conditional forwarding on PiHole to be able to have names of devices on the local network?

VLan (5): 192.168.5.1/24
PiHole : 192.168.5.3

I tried 192.168.5.1 and 192.168.1.1, along with my localdomain name, but this doesn't do the trick.

**Comment by boostchicken** [comment]
I will look into this, no clue why its not working.  You can hit your UDMs dnsmasq right?

Are you using iptables dnat?

**Comment by boostchicken** [comment]
@i-am-pierre might wanna try putting promisc on the interface.  I just updated the on_boot.sh scripts.  It solved a couple issues I was having.

**Comment by boostchicken** [comment]
@i-am-pierre have you had any success with this?  If there are no updates I will close the issue as stale

**Comment by boostchicken** [comment]
@i-am-pierre this will be fixed in PiHole 5.1

https://github.com/pi-hole/AdminLTE/pull/1208

**Comment by boostchicken** [comment]
@i-am-pierre, I found out why this is an issue. fix incoming
