### ISSUE TITLE
Suricata: Configuration Updates

### ISSUE THREAD

**Issue by mojo333** [boostchicken/udm-utilities#42]
While the new script to run v5.0.3 of Suricata worked okay, overlaying a newer version of Suricata means that the new configuration files are not being applied - see [https://suricata.readthedocs.io/en/suricata-5.0.3/upgrade.html#configuration-updates](https://suricata.readthedocs.io/en/suricata-5.0.3/upgrade.html#configuration-updates). According to the link these should be manually (or otherwise) updated if existing.

Comparing them:
- `reference.config`: identical
- `classification.config`: **out of date** 

Anyway to get these to be the updated versions to be automatically applied, as opposed to just updating manually? I'm fine with manual but not sure if/when they get overridden.

**Comment by boostchicken** [comment]
Can you show me an update to date one?

**Comment by mojo333** [comment]
Please see here: [https://github.com/jasonish/suricata/blob/master/etc/classification.config](https://github.com/jasonish/suricata/blob/master/etc/classification.config)

**Comment by boostchicken** [comment]
@mojo333 where am I supposed to update this?  Can you make a PR?

**Comment by mojo333** [comment]
I'm going to close this as I no longer use it. I may look into this again once I have time to investigate Suricata v6.
