### ISSUE TITLE
Support for hdd bay in UDMP

### ISSUE THREAD

**Issue by spali** [boostchicken/udm-utilities#43]
**Describe the solution you'd like**
The avoid future problems with the internal flash. Why not use the installed hard drive if available?
I just put in a empty drive and the UDMP formatted and mounted it at ```/mnt/data_ext```.
Would be great if the scripts would check the sub directories there too for scripts to execute and in that case would use also the drive for mounts.

Does anything speak against this, just wonder why didn't read something about using the additional drive here and in the reddit post :) 
To be honest just found you post and repo, but didn't had time to dig into it if there would be a problem to support it.

**Comment by SturdyErde** [comment]
I like the idea..but I also like the idea of a UDMP. 😀 Only have a UDM, or I would test for you.

**Comment by spali** [comment]
> I like the idea..but I also like the idea of a UDMP. 😀 Only have a UDM, or I would test for you.

Did anyone try to open the UDM Base? With a bit of luck there is a connector for any kind of storage soldered on it. At least had some luck with other devices where you wouldn't expect it, but could hold an USB stick or mSATA drive ;) And with the goal of ubiquity to use the same firmware for both... It may work then the same way ;)

**Comment by spali** [comment]
Had a quick look into the scripts.
If I'm not wrong, simply duplicate the if block at https://github.com/boostchicken/udm-utilities/blob/fd3f0b1a1d453af498b77e933c9a6b927f8d5d71/on-boot-script/dpkg-build-files/debian/postinst#L8
for ```/mnt/data_ext``` and a condtional (```-d /mnt/data_ext```) mkdir as in https://github.com/boostchicken/udm-utilities/blob/fd3f0b1a1d453af498b77e933c9a6b927f8d5d71/on-boot-script/dpkg-build-files/debian/postinst#L18 should work.
Same for the ```on_boot.sh``` copy.

**Comment by boostchicken** [comment]
@spali I dont have an HDD in my UDMP, and I want to keep targeting that market.

Maybe think of solution that supports both?

**Comment by spali** [comment]
Sure, shouldn't be a problem to support both. 
Will do a pull request when I have time.

**Comment by spali** [comment]
I'm gonna close this.
Just for people finding this:
works for at least for #50 by a simple symbolic link.
I think would work also for for the current release with links on `on_boot.sh` and `on_boot.d`.

**Comment by marceldarvas** [comment]
Anyone try https://github.com/ddominet/UDMPRO-samba ?
