### ISSUE TITLE
Support for OpenConnect VPN client

### ISSUE THREAD

**Issue by shuguet** [boostchicken/udm-utilities#48]
Hello there,

I've recently deployed an UDM-Pro and have successfully used your on-boot script to deploy my own OpenConnect VPN client container to connect to a GlobalProtect VPN server.

I've put all the files required in this repo if anyone wants to use it: https://github.com/shuguet/openconnect-udm

Best regards.

**Comment by boostchicken** [comment]
@shuguet This is awesome!  Send a PR to my repo!  I would love to use this personally as well!

**Comment by shuguet** [comment]
It lacks proper documentation...

Also, because of the way OpenConnect works with the particular Global Protect VPN endpoint I'm using (requires a 2FA auth based on an Okta prompt) I actually didn't put the connection script in the container image itself.

Instead I just put a generic entrypoint shell script in there that does nothing.
I pre-loaded the binaries for TOTP creation and the openconnect client in the image.
Then I bind-mount a shell script from a `/mnt/data` dir.
And finally I overload the command at runtime to execute that script instead of the built-in info-message/generic entrypoint script.

**Comment by boostchicken** [comment]
Well, let me link it on the main page at least for you.
