### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by chessgriffin** [boostchicken/udm-utilities#51]
It is not clear how to uninstall the boot scripts or the addons like NextDNS.  Can you please add instructions?  Thanks!

**Comment by theeddie** [comment]
I have tried 3 times now nextdns uninstall says it works but after a reboot this crap program comes back pushing my cpu to 100%

**Comment by spali** [comment]
Boot scripts are executed by the udm-boot dpk package you installed inside the unifi-shell.
Can be uninstalled from unifi-shell
```dpkg -p udm-boot```
After that when you reboot your udm, nothing from here should be started.
If you want, you can cleanup manually all the boot scripts and potential installed cni plugins etc.
