### ISSUE TITLE
Add capabilities to pihole for DHCP to work

### ISSUE THREAD

**Issue by mtritab** [boostchicken/udm-utilities#55]
Need to add `--cap-add=CAP_SYS_NICE,CAP_NET_ADMIN` to pihole-run in order for the container to start with DHCP enabled.

**Comment by SturdyErde** [comment]
This should be an optional setting for users to add (or not) when they set up their UDM utilities. I would suggest submitting a pull request on the wiki to add documented steps for those who want to use it.

**Comment by boostchicken** [comment]
this is optional and I am not going to open this can of worms in the default documentation, we will destroy many UDMPs. 

Don't forget, the average user of this repo is very green.
