### ISSUE TITLE
it won’t download.

### ISSUE THREAD

**Issue by MatthewGCampbell** [boostchicken/udm-utilities#57]
I go into the unifi-os shell and run the first command which downloads the github repo, and it doesn’t seem to download.
![IMG_0515](https://user-images.githubusercontent.com/31420840/95745915-f1071180-0c63-11eb-9773-28dc68bb2b37.png)

**Comment by SturdyErde** [comment]
That says 100%. Does the file still not exist on your filesystem?

**Comment by MatthewGCampbell** [comment]
correct. 
![IMG_0517](https://user-images.githubusercontent.com/31420840/95747135-ebaac680-0c65-11eb-9b07-1f0132b5aaf2.png)

**Comment by MatthewGCampbell** [comment]
at least it looks like dpkg can’t find it.

**Comment by firedfly** [comment]
@MatthewGCampbell - In your second screenshot (with the dpkg error), it doesn't look like you are in the unifi-os shell.  Can you try the dpkg command again from inside the unifi-os shell?

**Comment by MatthewGCampbell** [comment]
Yeah it works now. But it wasn’t working on 1.8.1 it is not working on the new beta.
