### ISSUE TITLE
Frequent disconnect events logged on UDMP (troubleshooting help)

### ISSUE THREAD

**Issue by scpotter** [boostchicken/udm-utilities#60]
**Describe the bug**
Looking into inconsistent connectivity issues saw that UDMP logs an event every 6 minutes where 10.0.5.1 disconnects from its dedicated “DNS” network. Not clear this is related to the project, looking for troubleshooting support. Running AdGuardHome.

**To Reproduce**
1. Go to web based UDMP Network page
2. Click on Events (calendar near bottom)
3. Filter on LAN and search for DNS (matches client alias and network)
4. See disconnect events

**Expected behavior**
See no events

**Screenshots**

**UDM Information**
 - Dream Machine Pro
 - Firmware Version: 1.8.0.2888 (current stable version?)
 - Controller Version: 5.14.22

**Additional context**

**Comment by boostchicken** [comment]
Close due to inactivity
