### ISSUE TITLE
Add Fhem Container & iptables problem udmp 1.8.2

### ISSUE THREAD

**Issue by RW-7** [boostchicken/udm-utilities#61]
Hello, I have now successfully got pihole to run on the udmp 1.8.2-5.
only didn't want to regulate the firewall
I just had to change
"
iptables -t nat -A PREROUTING -p tcp! -s $ {IPV4_IP}! -d $ {IPV4_IP} --dport 53 -j DNAT --to $ {IPV4_IP}
iptables -t nat -A PREROUTING -p udp! -s $ {IPV4_IP}! -d $ {IPV4_IP} --dport 53 -j DNAT --to $ {IPV4_IP}
", but now you can.
What I am still missing would be fhem on the system, with external logs or mysql.

**Comment by boostchicken** [comment]
Do not host MySQL on the UDMP,  its too much. I don't know what is being asked here so I am closing.  Please add a concrete ask or question and re-open if you still need help
