### ISSUE TITLE
homebridge on U

### ISSUE THREAD

**Issue by hfagelnour** [boostchicken/udm-utilities#62]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by boostchicken** [comment]
So the only question here is the homebridge port, it seems to want 8080, but it is configurable.  All Docker containers I see require --net=host.

There are two approachs
1. Use --net=host and change the port from 8080
2. Someone test macvlan with the port 8080 and see if homebridge still works.

I don't know why homebridge needs host level network access, does anyone know?

**Comment by boostchicken** [comment]
Looks this this was done, merged into master

#72
