### ISSUE TITLE
DNS Redirect for pihole not on router

### ISSUE THREAD

**Issue by jhoward321** [boostchicken/udm-utilities#64]
I was running pihole on the UDM, but recently moved it to a pi out of concerns for flash writes and easier support for DoT/DoH. 

One of the best features of the dns script is forcing hard coded dns queries to be directed to the pihole container. This low level of networking isn't my specialty, but if I'm reading [this](https://github.com/boostchicken/udm-utilities/blob/master/dns-common/on_boot.d/10-dns.sh#L84) correctly, it looks like I should be able to comment out the rest of the script and just point this IP towards by physical pihole.

Does this sound correct?

**Comment by spali** [comment]
To be honest... never got really familiar with iptable rules. I come to the same conclusion.
Why you don't just try it out by executing it manually (so a reboot would resolve potential problems)?

**Comment by boostchicken** [comment]
That will write a iptables rule to move all DNS request to specified IP yes, you can steal it for anything else you want.

**Comment by bluewalk** [comment]
Quick question though regarding this issue/question :-)

I will be receiving my UDM Pro this week and need to do this as well (such a waste this isn't possible anymore with config.gateway.json).
It's easy to add it as a startup script. I am wondering though, are the rules also persistent when de firewall rules are provisioned from the controller?
