### ISSUE TITLE
add/join additional containers to an existing macvlan network 

### ISSUE THREAD

**Issue by ghvader** [boostchicken/udm-utilities#66]
I have pi hole set up and working, however i want to try and run other containers with the same network as pihole
i set up vlan 10 192.168.5.0/24
my pi hole runs 192.168.5.10
if i install other containers for other reason and want them to also use 192.168.5.xxx how can i do that?
I don't want to have to create a new vlan and new network for each and every container if possible.

**Comment by spali** [comment]
did not test it on podman from udm itself.
I experimented a bit with a "nested podman" with macvlan inside a container on the udm. But the nested podman had access to the host network (so should in theory behave more or less the same). 

First you need the cni plugin macvlan (if I remember right, in this repo is a somewhere a script for it).
Then you need to create a podman network with the macvlan plugin.
Then you can use this network with multiple containers with ```--network mynet```.
Google a bit for podman and macvlan network to get config file examples and how to set it up.

But before you start.... macvlan has one big drawback. Everything attached to a macvlan network can directly be in the hosts network, but cannot talk to the host itself directly (in this case the udm). So for example DHCP is not possible when the UDM is playing dhcp server. 
I read somewhere there exists a workaround with a second macvlan network, that acts like a router to workaround this issue, but here it gets definitely too complicated for me ;)

**Comment by boostchicken** [comment]
@ghvader you can add as many containers as you want to a single macvlan network. All that is required is learning the CNI plugins.  If you look at our CNI plugins we use the static ip ipam provider.  There are others for dhcp, handing out ips from a local range etc etc.  Just look at the CNI driver documentation and adjust accordingly

https://github.com/boostchicken/udm-utilities/blob/master/cni-plugins/20-dns.conflist

**Comment by boostchicken** [comment]
@ghvader 

https://github.com/boostchicken/udm-utilities/issues/77#issuecomment-751128983
