### ISSUE TITLE
Not working on UXG-Pro - questions on workaround

### ISSUE THREAD

**Issue by wjhanna** [boostchicken/udm-utilities#69]
I have a UXG-Pro (still in Early Access) and was hoping these scripts would be able to work on that, assuming they had the same UniFi OS backend.. which looks like its partially true. I can run some commands, but it looks like it's a seriously stripped down version. No docker, podman, dpkg, python, so it doesn't look like any of this works out of the box. I don't really know enough about this stuff on my own, but I'm more than willing to test/troubleshoot.

I'm wondering if there is any way to bring over the apps like docker? Do they need to be 'installed', or does /bin/docker from a UDM work? If there's no dpkg, is there no way to install anything? I've copied some files over into /mnt/ and it looks like files persist through reboots and firmware updates.

**Comment by wjhanna** [comment]
Marking this as closed, I'm sending the UXG-Pro back and getting a UDMP.

I posted this on the Ubiquiti forums and was told this will not work on the UXG-Pro due to how it's set up at the OS level: The UDM/P uses containers for the appliance, controller, etc, which is why it has that functionality baked in. The UXG-Pro is bare metal and doesn't need it as its intended to be a gateway only.

**Comment by boostchicken** [comment]
I am 1000% positive if I got my hands on a UXG-Pro I could get Podman and these scripts here working.  I am not going to buy a device to do that though, if someone wants to donate one I would be happy to do it.

However @wjhanna you are correct.  The UDMP functionality and market segment wise is positioned more as the app server.  The UXG is more high end gateway.

**Comment by cswelin** [comment]
@boostchicken Just to note UXG 0.5 update has pod man installed, haven't tried to use it yet.

**Comment by hagmonk** [comment]
@boostchicken just FYI, since I've been digging around here … I think this will be kind of difficult. In that I can't see an obvious way to persist a boot script. The current set of udm-utilities scripts, from what I can tell, rely on systemd being started inside a "unifi-os" container. The UXG-Pro appears to do things differently.

It starts a container called `uxg-setup`:

```
# podman ps -a
CONTAINER ID  IMAGE                       COMMAND               CREATED     STATUS         PORTS  NAMES
7cd3e192faf5  localhost/uxg-setup:latest  nodejs /usr/share...  8 days ago  Up 8 days ago         uxg-setup
```

Whose entrypoint and command are:

```
        "Path": "docker-entrypoint.sh",
        "Args": [
            "nodejs",
            "/usr/share/uxgpro-setup/app.js"
        ],
```

`docker-entrypoint.sh` is just a bash script to exec `node`. So I can't see any hooks here that would enable running a script. The processes inside the container:

```
root@UXG-Pro:/# ps waux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  2.0  7.2 975472 139868 ?       Ssl  Feb27 260:45 nodejs /usr/share/uxgpro-setup/app.js
root      7727  1.0  0.1   3740  2960 pts/0    Ss   01:56   0:00 bash
root      7734  0.0  0.1   5380  2292 pts/0    R+   01:56   0:00 ps waux
```

The boot partition user space is all Busybox. Scripts in /etc/init.d/ are run, the most interesting of which kicks off `/etc/init.d/S95uxgsetup` which actually starts the uxg-setup container. 

There is some stuff in here about systemd but perhaps it's vestigial? 

```
mount_systemd_cgroup() {
        # make sure to provide systemd with the control group it expects
        local systemd_mount=/sys/fs/cgroup/systemd
        grep -q "${systemd_mount}" /proc/mounts || {
                mkdir -p "${systemd_mount}"
                mount -t cgroup cgroup \
                                        -o none,name=systemd,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent \
                                        "${systemd_mount}"
        }
}
```

The mounts are all files except for mounting `/etc/` into `/etc_host` inside the container:

```
set_mounts() {
        local ssh_dir=/mnt/data/ssh
        ensure_ssh_key "${ssh_dir}"

        MOUNTS="--mount type=bind,source=/usr/lib/version,target=/usr/lib/version,ro=true"
        MOUNTS="${MOUNTS} --mount type=bind,source=${ssh_dir}/id_rsa,target=/root/.ssh/id_rsa,ro=true"
        MOUNTS="${MOUNTS} --mount type=bind,source=/etc,target=/etc_host,ro=true"
        MOUNTS="${MOUNTS} --mount type=bind,source=/usr/bin/ubios-udapi-client,target=/bin/ubios-udapi-client,ro=true"
        MOUNTS="${MOUNTS} --mount type=bind,source=/usr/bin/mca-dump,target=/usr/bin/mca-dump,ro=true"
        MOUNTS="${MOUNTS} --mount type=bind,source=/sbin/ubnt-systool,target=/sbin/ubnt-systool,ro=true"
        MOUNTS="${MOUNTS} --mount type=bind,source=/usr/sbin/ntpd,target=/usr/sbin/ntpd,ro=true"
}
```

start function in its entirety:

```
start() {
        local args
        local image_version

        image_version=$(get_version "${IMAGE_NAME}:default")

  mount_systemd_cgroup
        set_mounts
        if container_exists "${CONTAINER_NAME}"; then
                if container_is_running "${CONTAINER_NAME}"; then
                        echo "${CONTAINER_NAME} is already running"
                        return 0
                fi
                container_version=$(get_version "${CONTAINER_NAME}")
                if [ "$container_version" != "$image_version" ]; then
                        echo "version mismatch, container has version ${container_version}, wanted ${image_version}, recreating container"
                        podman rm "${CONTAINER_NAME}" --force
                        podman rmi "${IMAGE_NAME}:default" &>/dev/null || true
                        podman rmi "${IMAGE_NAME}:${IMAGE_TAG}" || true
                        start
                        return
                fi
        fi

        echo "Starting ${CONTAINER_NAME}"

        while [ ! -L /etc/resolv.conf ] || [ ! -e /etc/resolv.conf ]; do sleep 1; done
        sleep 1

        for attempt in 1 2; do
                if ! container_exists "${CONTAINER_NAME}"; then
                        args="-d --name ${CONTAINER_NAME} --label version=${image_version} --network=host --privileged  --stop-timeout=60 ${MOUNTS}"

                        if image_exists "${IMAGE_NAME}:${IMAGE_TAG}"; then
                                create_container "$args" "${IMAGE_NAME}:${IMAGE_TAG}" ||
                                {
                                        echo "Starting container from ${IMAGE_NAME}:${IMAGE_TAG} failed, falling back to default"
                                        create_container "$args" "${IMAGE_NAME}:default" ||
                                        echo "Starting container from ${IMAGE_NAME}:default failed" >&2
                                }
                        else
                                create_container "$args" "${IMAGE_NAME}:default" ||
                                echo "Starting container from ${IMAGE_NAME}:default failed" >&2
                        fi
                fi

                podman start "${CONTAINER_NAME}" && return 0
                echo "Starting ${CONTAINER_NAME} attempt $attempt failed"

        done
}
```

Happy to provide more detail if you're interested!

**Comment by rhdny** [comment]
@hagmonk - thanks for giving it a shot and posting. I was curious myself.

**Comment by dotgrid** [comment]
@boostchicken 

John, I can get you a UXG-PRO—in your hands, for actual testing. (It’s the least I can do, given how incredibly helpful your scripts have been for me.)

What’s the best way for us to exchange info privately, so I can get a shipping address?

**Comment by joshuaspence** [comment]
@dotgrid FYI I have a working solution for the UXG-Pro. It's not my original idea but I've packaged it up for easy installation. My repo is https://github.com/joshuaspence/uxg-setup and I will add instructions for use to the readme today

**Comment by dotgrid** [comment]
> FYI I have a working solution for the UXG-Pro. It's not my original idea but I've packaged it up for easy installation. My repo is https://github.com/joshuaspence/uxg-setup and I will add instructions for use to the readme today

@joshuaspence This looks very promising! Amazing!

I have installed it successfully. But, I will need to wait for your expanded readme to really get to grips with what I can do next :) Thanks for sharing this!

**Comment by joshuaspence** [comment]
@dotgrid I have added to the README and the repo is generally in a good state I think. Let me know if you think there's anything missing (from the README that is)

**Comment by boostchicken** [comment]
Thanks to @dotgrid for the UXG Pro, a man of his word!

**Comment by joeykrim** [comment]
Much more useful information in separate issue: https://github.com/unifi-utilities/unifios-utilities/issues/356
