### ISSUE TITLE
Not working on UDM (not PRO)

### ISSUE THREAD

**Issue by michaelpneuman** [boostchicken/udm-utilities#73]
The newest UDM (details below) doesn't appear to be running unifi-os container or use docker/podman at all.  It's a straight overlay filesystem.   Process doesn't seem to work there.

# cat /etc/os-release
NAME=UbiOS
VERSION=UDM.alpinev2.v1.5.6.615c4d9.200327.1930
ID=ubios
VERSION_ID=v1.5.6.2150-615c4d9
PRETTY_NAME="UbiOS 1.5.6.2150"
BUILD_ID=200327.1930
VARIANT=UDM.alpinev2

**Comment by michaelpneuman** [comment]
I'm closing this issue--the standard firmware will not work.  I had to upgrade to the beta track of 1.8.0.  With 1.8.0 they have the containerized version of the OS.

**Comment by SturdyErde** [comment]
In case you missed it, this project's documentation shows that it should work on any UDM/UDMPro after 1.6.3. It has been tested and confirmed on 1.6.6, 1.7.0, 1.7.2rc4, 1.7.3rc1, 1.8.0rc7, and 1.8.0,

**Comment by michaelpneuman** [comment]
Thank you!  I did miss that and was digging around thinking that to be the
case.  Works perfectly now.
--
