### ISSUE TITLE
Unable to install, or access podman.

### ISSUE THREAD

**Issue by Hammerkeg** [boostchicken/udm-utilities#74]
**Describe the bug**
Unable to install, or access podman.

```
Setting up udm-boot (1.0.2) ...
lost connection
dpkg: error processing package udm-boot (--install):
 subprocess installed post-installation script returned error exit status 1
```

**UDM Information**
 - Dream Machine Pro
 - Firmware Version: 1.8.3
 - Controller Version 6.0.41

**Additional context**
I know this is probably a firmware issue, but I'd like to report it.

**Comment by SturdyErde** [comment]
Did this just happen when you updated the controller to 6.0.41?

**Comment by Hammerkeg** [comment]
Unfortunately, I can't tell which version caused this, as I hadn't tried either of the commands since about 6.0.36 or maybe even earlier.
I had to reset my UDM-P to factory yesterday, and that wiped all my existing data, specifically wireguard, which I now can't install.

**Comment by SturdyErde** [comment]
I'm running UDM base with firmware 1.8.3 beta 2 and version 6.0.36 of the controller. Everything is good here so far. It's hard to imagine them making that drastic a change in Unifi OS in such a short span. Now I have a morbid temptation to update and find out!

**Comment by mgworek** [comment]
I am unable to access podman as well. I just upgraded to 1.8.4-2 today. Everything runs fine after the second reboot but I was going to switch to pihole from Adguard but can't run podman. At least adguard is still running.

**Comment by SturdyErde** [comment]
What is the error you get when running podman? I just updated to the official 1.8.3 release with version 6.0.41 of the controller, and podman is working fine. Do the release notes for the 1.8.4 betas mention anything about changes to podman or docker?

**Comment by Hammerkeg** [comment]
Well, I just realized access to docker/podman is through the regular unifi shell, and not through the one accessed by unifi-os shell.

**Comment by SturdyErde** [comment]
That would do it! Case closed?

**Comment by mgworek** [comment]
> Well, I just realized access to docker/podman is through the regular unifi shell, and not through the one accessed by unifi-os shell.

Ok i am being brain dead and forgetting how I did this the first time. I double check all the readmes and I thought I went into unifi-os shell to do this and that is where podman is not working. How do I get into the other shell? Don't worry, I will feel stupid when I figure this out.....

**Comment by SturdyErde** [comment]
Do not go into the Unifi-OS shell. That is actually running in its own container. Just SSH to your UDM[P] and run the commands. eg: `podman container list`.

**Comment by mgworek** [comment]
> Do not go into the Unifi-OS shell. That is actually running in its own container. Just SSH to your UDM[P] and run the commands. eg: `podman container list`.

Like I said, I feel stupid. When I got the error running it from in the OS shell and then just ran outside of the shell, my mind was telling me i was getting the same error but it was really telling me I needed a command with podman.

Sorry about that..... It has been way to long since I played with this awesome set of utilities.....

Going back into my corner now....
