### ISSUE TITLE
PiHole UI crashes when making any changes

### ISSUE THREAD

**Issue by Tragyn** [boostchicken/udm-utilities#76]
**Describe the bug**
Pihole container crashes when trying to make any changes in the UI

**To Reproduce**
Go to 10.0.5.3, login, change any setting (change theme, add blocklist, etc)

**Expected behavior**
The thing to change, and the UI not to crash.

**Screenshots**

**UDM Information**
 - Dream Machine Pro
 - Firmware Version: 1.8.3
 - Controller Version: 6.0.41

**Additional context**
None, but please let me know if I can provide anything.

**Comment by Tragyn** [comment]
PiHole was dead all evening... sorted itself out overnight apparently.  I have no idea what happened but it seems to be working now.

![12 06 20-08:41:04](https://user-images.githubusercontent.com/5403547/101284759-def6aa80-379e-11eb-98ef-b56016c1e8a7.png)

**Comment by Tragyn** [comment]
Happening again.  I can't find any kind of pattern to it.

**Comment by Tragyn** [comment]
Now I'm not certain it has crashed.  I can still ping it.

**Comment by boostchicken** [comment]
Does restarting the container fix it?

**Comment by Tragyn** [comment]
> Does restarting the container fix it?

Restarting the container and/or unifi-os doesn't bring it back immediately.  I have no idea why, but it starts working again several hours after I leave it alone. For example, yesterday I gave up on it at about 6PM, and it started working at approximately 12PM, and I have no idea why.

![12 24 20-15:33:42](https://user-images.githubusercontent.com/5403547/103107614-6ea0b380-45fd-11eb-8c36-ae1bbda52d79.png)

**Comment by boostchicken** [comment]
ANything in syslog?  How is the resource utilization on your UDMP?

**Comment by Tragyn** [comment]
Nothing in the logs is standing out to me, though I do see the pihole container restarting on its own. I'll try to reproduce the error and see if I can narrow down some times, but until now here's my log.

UDM utilization is averaging about 27% in the last 24 hours.  It's a fairly simple network with only one AP and fewer than 30 clients so I don't think that's an issue (I hope).

[messages.txt](https://github.com/boostchicken/udm-utilities/files/5740663/messages.txt)

**Comment by Tragyn** [comment]
When I reboot my UDM-P I see this in my log (313eb51... is pihole), which results in pihole not being autostarted.

> Dec 26 16:37:04 Dream-Machine-Pro user.notice unifi-os: time="2020-12-26T09:37:04-07:00" level=error msg="CNI network \"dns\" not found"
Dec 26 16:37:04 Dream-Machine-Pro user.notice unifi-os: time="2020-12-26T09:37:04-07:00" level=error msg="Error refreshing container 313eb51cb6d040a12e81ba2730cac449c63d3c7c6807f3a540f80aa00ba0e096: CNI network \"dns\" not found"
Dec 26 16:37:04 Dream-Machine-Pro user.notice unifi-os: time="2020-12-26T09:37:04-07:00" level=error msg="Error deleting network: failed to find plugin \"portmap\" in path [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin]"
Dec 26 16:37:04 Dream-Machine-Pro user.notice unifi-os: time="2020-12-26T09:37:04-07:00" level=error msg="Error while removing pod from CNI network \"podman\": failed to find plugin \"portmap\" in path [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin]"
Dec 26 16:37:04 Dream-Machine-Pro user.notice unifi-os: time="2020-12-26T09:37:04-07:00" level=error msg="Error refreshing container 3757570e0516a6f7e461a83fb561996fd165e1d4996e5e9ddc38ee6be34dda4e: failed to find plugin \"portmap\" in path [/usr/libexec/cni /usr/lib>
Dec 26 16:37:04 Dream-Machine-Pro user.notice unifi-os: time="2020-12-26T09:37:04-07:00" level=error msg="CNI network \"dns\" not found"
Dec 26 16:37:04 Dream-Machine-Pro user.notice unifi-os: time="2020-12-26T09:37:04-07:00" level=error msg="Error refreshing container 6ff9ac7ea2e066ac0f93e55124d82092f5e21b0f94976e88cfe99a935d1f980b: CNI network \"dns\" not found"

**Comment by Tragyn** [comment]
As is tradition, it was user error.

in 10-dns.sh I had "nextdns" instead of "pihole".  Fixed that and all is well.
