### ISSUE TITLE
Multiple pihole containers

### ISSUE THREAD

**Issue by nathasm** [boostchicken/udm-utilities#77]
**Describe the bug**
I want to run multiple pihole containers on a UDMP. I believe this should be possible? Let me know if you have any ideas or things to try.

**To Reproduce**

I created a second corporate network in my controller and then added an additional network to the 20-dns.conflist as:

```
{
      "type": "macvlan",
      "mode": "bridge",
      "master": "br6",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.0.6.3/24",
            "gateway": "10.0.6.1"
          }
        ],
        "routes": [
          {"dst": "0.0.0.0/0"}
        ]
      }
    }
```

Finally, I created and ran /mnt/data/on_boot.d/11-dns.sh which is a copy of 10-dns.sh but with the configuration variables changed as:

```
## configuration variables:
VLAN=6
IPV4_IP="10.0.6.3"
IPV4_GW="10.0.6.1/24"
```

And then tried to create an additional container.

Upon doing so, I saw the following errors:

```
ERRO[0001] Error adding network: failed to rename macvlan to "eth0": file exists
ERRO[0001] Error while adding pod to CNI network "dns": failed to rename macvlan to "eth0": file exists
ERRO[0001] Error removing timer for container 6697fefd6eb60155565b08d8aec4c67cf339ba975a5143620dd84504ae43b226 healthcheck: unable to get systemd connection to remove healthchecks: dial unix /run/systemd/private: connect: no such file or directory
Error: error configuring network namespace for container 6697fefd6eb60155565b08d8aec4c67cf339ba975a5143620dd84504ae43b226: failed to rename macvlan to "eth0": file exists
```

**Expected behavior**
Is this possible?

**UDM Information**
 - Variant: Dream Machine Pro
 - Firmware Version: Latest
 - Controller Version Latest

**Comment by SturdyErde** [comment]
Duplicate of [#66 add/join additional containers to an existing macvlan network](add/join additional containers to an existing macvlan network). The examples that you provided are good, but will be most useful in one issue discussion.

**Comment by nathasm** [comment]
Thanks! Didn't see that issue before creating a new one...closing this as it is a duplicate.

**Comment by boostchicken** [comment]
@nathasm commented in the other issue with details regarding multiple ips on the same macvlan

In your network conflist change the IPAM structure to match something like this.
https://www.cni.dev/plugins/ipam/host-local/

Then in your 10-dns.sh make sure you update the routes to send your whole network block, not just the ip across the br5.mac device.

Every time you start a container, Podman will hand out the next available ip address.  Sadly since the podman binary is out of date on the UDMP you cannot specify an IP in the command line.
