### ISSUE TITLE
How to SSHuttle into a UDM Pro

### ISSUE THREAD

**Issue by AddoSolutions** [boostchicken/udm-utilities#78]
**Is your feature request related to a problem? Please describe.**
I need to SSHuttle into UDM machines for more convenient VPN and easier connectivity
**Describe the solution you'd like**
How to connect, as python is not available in the root OS

**Additional context**
The problem is that `unifi-os` is actually a docker container, and this we cannot access it directly

**Comment by AddoSolutions** [comment]
I want to solve my own issue, just to document for other users.  This is super hacky, but does in fact work.

First, you will need to figure out a name of a directory (theres probably a symlink somewhere but I didn't see it off hand). You will need to figure out exactly your path is, mine is something like:

`/var/lib/containers/storage/overlay/l/UVJVRAPPXXXXX7HHP/usr/bin/python3`

```
sshuttle -r my.domain.com --python "/var/lib/containers/storage/overlay/l/UVJVRAPPXXXXX7HHP/usr/bin/python3" 10.0.0.0/16
```

Then you can get in.  You are technically using a binary for python that is linked to a different OS, so expect bugs, but so far so good on my end!

**Comment by SturdyErde** [comment]
Interesting! You could probably add this to the wiki so it doesn't look like an open issue. That would also allow you to create neater documentation and explanation. If the wiki is protected, just submit it as a pull request to the wiki.

**Comment by boostchicken** [comment]
https://github.com/boostchicken/udm-utilities/tree/master/python

The solution has been there for a while. That will link up python3 in your path on boot.  Living in the danger zone, I like it!

**Comment by AddoSolutions** [comment]
@boostchicken thats a different solution that what I mentioned. The solution I provided works on an UNMODIFIED UDM, the solution you mentioned requires you to be install and/or change files on the device.
