### ISSUE TITLE
Need Some Help to run OpenWRT in podman

### ISSUE THREAD

**Issue by DaCapone1986** [boostchicken/udm-utilities#79]
Hi Guys,

Can somebody help me Please to run OpenWRT on My UDM Pro. I realy need Ds-lite Support, maybe this is a workaround
My Wish is to run Openwrt and Pihole

maybe this one, seems Up to date : https://hub.docker.com/r/unifreq/openwrt-aarch64

Best Regards

**Comment by SturdyErde** [comment]
That Docker container doesn't show any documentation or links to code in GitHub. Have you found a way to review it before installing? I haven't used DS-Lite myself, but is this what you're looking to run on your UDM? If so, I'm curious about your use case.

> "Dual Stack Lite (DS-Lite) is an IPv6 transition solution for ISPs with IPv6 infrastructure to connect their IPv4 subscribers to the Internet."
https://docs.citrix.com/en-us/citrix-adc/current-release/citrix-adc-support-for-telecom-service-providers/dual-stack-lite.html

**Comment by SturdyErde** [comment]
@alsmith created a [multicast-relay](https://github.com/alsmith/multicast-relay) project that runs on UDM and looks like it utilizes some OpenWRT bits. Perhaps that repo or even the developer himself could be a resource for your next steps.

**Comment by alsmith** [comment]
Unfortunately, while I did get instructions together to allow the relay project to run in OpenWRT, I’m afraid I don’t think I’m au fait enough with OpenWRT to be able to offer much assistance here.

Sorry!

Appreciate the props though @SturdyErde!

**Comment by DaCapone1986** [comment]
> That Docker container doesn't show any documentation or links to code in GitHub. Have you found a way to review it before installing? I haven't used DS-Lite myself, but is this what you're looking to run on your UDM? If so, I'm curious about your use case.
> 
> > "Dual Stack Lite (DS-Lite) is an IPv6 transition solution for ISPs with IPv6 infrastructure to connect their IPv4 subscribers to the Internet."
> > https://docs.citrix.com/en-us/citrix-adc/current-release/citrix-adc-support-for-telecom-service-providers/dual-stack-lite.htm

Yes that is the reason, my thought was to let Openwrt manage the vlan.
does anyone have another idea how to make DS-Lite possible on the UDM

**Comment by DaCapone1986** [comment]
success!

i got one runnig,
**correct me** if i am wrong, please!
first create a VLAN only network in my example **vlan100**

**podman run --restart always -d --net openwrt --name OpenWrt minirailgun/openwrt-aarch64:latest /sbin/init**
after that 
**podman exec -it OpenWrt /bin/sh**
then edit the network in OpenWrt image
**vi /etc/config/network**
press i for insert, then copy paste the example. press ESC type **:wq** then enter
example:

config interface 'loopback'
        option ifname 'lo'
        option proto 'static'
        option ipaddr '127.0.0.1'
        option netmask '255.0.0.0'

config globals 'globals'
        option ula_prefix 'fdc8:a9bc:7bd4::/48'

config interface 'lan'
        option type 'bridge'
        option ifname 'eth0'
        option proto 'static'
        option ipaddr '192.168.100.100'
        option netmask '255.255.255.0'
        option ip6assign '60'
        option gateway '192.168.100.1'
        option dns '192.168.1.1'

**Comment by alsmith** [comment]
Awesome!!

**Comment by DaCapone1986** [comment]
how can i run a container that is already created and customized with --privileged root rights
and how to create a image from a working container^^

thx for help

**Comment by DaCapone1986** [comment]
Can someone help me to run this container native on localhost( —net host) 
it exits with code 137
And i dont know how to config the interface to reach the webif

best regards

**Comment by boostchicken** [comment]
I would not run this with --net host.

Does someone want to package this into a commit so we can put it in the actual repo? @alsmith @DaCapone1986
