### ISSUE TITLE
udmboot.service After in wrong section

### ISSUE THREAD

**Issue by exodious** [boostchicken/udm-utilities#8]
**Describe the bug**
The `After=network.target` line in udmboot.service is in the wrong section. It belongs in `[Unit]` not `[Service]`. A warning is emitted:
```shell
Jun 19 22:14:17 ubnt systemd[1]: /etc/systemd/system/udmboot.service:4: Unknown lvalue 'After' in section 'Service', ignoring
```

**To Reproduce**
Run the installer or manual instructions, then check the log in the unifi-os container.

**Expected behavior**
No warning messages to be emitted.

**UDM Information**
 - Variant: Dream Machine Pro
 - Firmware Version: 1.7.2
 - Controller Version: 5.13.30

**Additional context**
See https://www.freedesktop.org/software/systemd/man/systemd.unit.html and https://www.freedesktop.org/software/systemd/man/systemd.service.html

**Comment by boostchicken** [comment]
Thanks! Merged!
