### ISSUE TITLE
Feature Nginx proxy manager

### ISSUE THREAD

**Issue by skynett81** [boostchicken/udm-utilities#81]
Feature for UDM PRO

**Describe the solution you'd like**
I want a solution on having both SSL and Proxy in a same app . 

so i hope Nginx Proxy Manager  could bee supported .
https://nginxproxymanager.com/

**Comment by faust86** [comment]
plus from me 👍

**Comment by boostchicken** [comment]
I am going to go ahead and say no and close this one down.  NGINX Proxy Manager requires a MySQL database running as well.  That is jsut too much for the UDMP.  This is better suited for another device.  Running NGiNX vanilla itself is super easy on the UDMP with a few podman commands

**Comment by boostchicken** [comment]
Also if you need Lets Encyprt

https://github.com/kchristensen/udm-le
