### ISSUE TITLE
ssh keys?

### ISSUE THREAD

**Issue by MatthewGCampbell** [boostchicken/udm-utilities#83]
A lacking feature with the UDM Pro is the ability the add SSH keys, since it remakes and deletes any keys you transfer upon reboot. I'm trying to see if i could use the on boot script to maybe mitigate these issues, but i was first wondering if anyone had already gotten something like this working.

**Comment by lorenzocanalelc** [comment]
I did it, I used an on boot script called "10-publickeys.sh" in the on_boot.d folder

It contains this:
```
#!/bin/sh

# Copy My MacBook Public Key
echo "INSERT_YOUR_PUBLIC_KEY_HERE" >> ~/.ssh/authorized_keys
```

**Comment by MatthewGCampbell** [comment]
> I did it, I used an on boot script called "10-publickeys.sh" in the on_boot.d folder
> 
> It contains this:
> 
> ```
> #!/bin/sh
> 
> # Copy My MacBook Public Key
> echo "INSERT_YOUR_PUBLIC_KEY_HERE" >> ~/.ssh/authorized_keys
> ```

I am needing both the public and private keys so i can allow a automated scp cert transfer from a server, if I need basically the entire /.ssh folder (authorized_keys, private key, public key) would echo be the best route?

**Comment by JKomoroski** [comment]
Consider using a here doc in your scipt.

Example of the syntax:
```
cat <<'EOF' >> /my/file/output.txt
This text box will be written to 
the output text file
and new lines are easy to read
since i use the 'EOF' in quotes 
to signify the end of file, no ${variables}
will be interpolated
EOF
```

https://tldp.org/LDP/abs/html/here-docs.html

**Comment by boostchicken** [comment]
@MatthewGCampbell wanna make a PR with your script to throw into the actually repo?

**Comment by MatthewGCampbell** [comment]
Yeah I got it working thank you guys wasn’t sure what the best route was. Thanks to @lorenzocanalelc

**Comment by boostchicken** [comment]
@MatthewGCampbell Cool are you going to add it to the repository via a Pull Request?

**Comment by MatthewGCampbell** [comment]
I guess I could but it’s @lorenzocanalelc who made the script and commented it, I’d be happy to do so if he can’t

**Comment by lorenzocanalelc** [comment]
@MatthewGCampbell You can do it, it's fine for me

**Comment by boostchicken** [comment]
Close this. Great work. Thanks!
