### ISSUE TITLE
Possible WIFI slowdown on UDM Base (not PRO)

### ISSUE THREAD

**Issue by Eric-Vignola** [boostchicken/udm-utilities#87]
I recently upgraded my stock UDM Base firmware from 1.5.2 to 1.8.4 specifically to use your tools. I am currently running your on boot scripts. 

I am currently running:
10_dns.sh
20_wpa_supplicant.sh  (to bypass ATTs modem)
30_pihole.sh

Everything is working like a charm except for one issue: WIFI speed has come down quite a bit. On my iPhone standing next to the UDM i used to get ~400Mbps, and now i get about ~140Mbps.  Wired computers are working like before, in the ~900Mbps range (ATT Gigabit fiber).

Trying to debug this, i see nothing in the UDM's settings i would have changed to cause this. So i am wondering if anyone else has had similar issues after installing the onboot scripts.

**Comment by boostchicken** [comment]
Check the resource utilization on the UDM.   Do you have IPS/IDS running?

**Comment by Eric-Vignola** [comment]
utilization is at 34%, Internet Threat Management is off as well as Traffic
and device identification.

**Comment by andrewmiskell** [comment]
Double check your channel width settings on the AP. That's usually the issue. Getting only ~150mbps sounds like your channel width has reverted back to 20mhz.

I'm running on 1.8.4 with onboot scripts (custom dnsmasq settings and wpa_supplicant for AT&T) and I'm getting 500+ mbps in both directions on my iPhone 12 Pro Max.

**Comment by Eric-Vignola** [comment]
> Double check your channel width settings on the AP. That's usually the issue. Getting only ~150mbps sounds like your channel width has reverted back to 20mhz.
> 
> I'm running on 1.8.4 with onboot scripts (custom dnsmasq settings and wpa_supplicant for AT&T) and I'm getting 500+ mbps in both directions on my iPhone 12 Pro Max.

These are settings i've never touched before, but in any case my current settings are:
2G radio: VHT20  channel: auto
5G radio: VHT40  channel: auto

let me know what yours are set to if you don't mind.

**Comment by andrewmiskell** [comment]
> > Double check your channel width settings on the AP. That's usually the issue. Getting only ~150mbps sounds like your channel width has reverted back to 20mhz.
> > I'm running on 1.8.4 with onboot scripts (custom dnsmasq settings and wpa_supplicant for AT&T) and I'm getting 500+ mbps in both directions on my iPhone 12 Pro Max.
> 
> These are settings i've never touched before, but in any case my current settings are:
> 2G radio: VHT20  channel: auto
> 5G radio: VHT40  channel: auto
> 
> let me know what yours are set to if you don't mind.

I use VHT20 on 2G (due to congestion around me) on VHT80 on 5G. I manually select my channels after doing a RF scan to determine what channels are the least congested around me and select those channels.

**Comment by Eric-Vignola** [comment]
that was it. Somehow upgrading the firmware must have changed the setting. With 5G at VHT80 i'm back at 500+Mbps wifi.

Sorry for the noise everyone! Immensely grateful for the work being done here.
