### ISSUE TITLE
Guide to update pihole to latest (pi-hole, Web interface, FTL)

### ISSUE THREAD

**Issue by smegoff** [boostchicken/udm-utilities#91]
I have recently installed pi-hole under the UDM Pro. 

I realise now (being a bit green) that you can not issue a pihole -up command via podman as this isnt supported in docker images.

My reseach suggests that you have to remove and re-add the image to the latest by running:

` podman run -d --network dns --restart always \
    --name pihole \
    -e TZ="America/Los Angeles" \
    -v "/mnt/data/etc-pihole/:/etc/pihole/" \
    -v "/mnt/data/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/" \
    --dns=127.0.0.1 \
    --dns=1.1.1.1 \
    --dns=8.8.8.8 \
    --hostname pi.hole \
    -e VIRTUAL_HOST="pi.hole" \
    -e PROXY_LOCATION="pi.hole" \
    -e ServerIP="10.0.5.3" \
    -e IPv6="False" \
    pihole/pihole:latest`

What is the process to safely remove the image prior to running this again.

Is it possible to build a "centralised" script to perform various tasks like updating the boot scripts, and updating pi-hole?

**Comment by techandbeers** [comment]
Hey @smegoff,

Please see: https://github.com/boostchicken/udm-utilities/wiki/Update-Containers

You could certainly make a simple script containing the commands mentioned in the wiki article above in combination with your custom podman run.

**Comment by smegoff** [comment]
> 
> 
> Hey @smegoff,
> 
> Please see: https://github.com/boostchicken/udm-utilities/wiki/Update-Containers
> 
> You could certainly make a simple script containing the commands mentioned in the wiki article above in combination with your custom podman run.

Awesome thanks!

**Comment by smegoff** [comment]
Hi @techandbeers 

It must be too early in the morning - however, to pull down the latest pi-hole image in this situation, "podman pull docker.io/path/to/application" I cant see in @boostchicken's scripts where it grabs the pi-hole image from?

Still a little green on this one. Learning a lot though! 👍

**Comment by techandbeers** [comment]
@smegoff Hey we all start somewhere! Should be good with:

`podman pull pihole/pihole`

**Comment by smegoff** [comment]
> 
> 
> @smegoff Hey we all start somewhere! Should be good with:
> 
> `podman pull pihole/pihole`

Thanks for the help - I have updated the wiki too 👍

**Comment by SturdyErde** [comment]
Does the wiki page on [updating containers](https://github.com/boostchicken/udm-utilities/wiki/Update-Containers) sufficiently cover this for you? I don't think automatically-updating containers would be desirable, as you would lose the opportunity to plan and test something that is used by your entire network.

**Comment by smegoff** [comment]
Hi Sam,

I actually wrote half of that wiki a few weeks ago.

Cheers

Sean

**Comment by SturdyErde** [comment]
Yes, sorry if not clear: I meant to acknowledge that, and am curious if the wiki is complete enough to close the issue/request. If not, what further information would be needed?

**Comment by smegoff** [comment]
Hi Sam,

I believe it is enough to update pi-hole containers, thank you.

Please close the request.

Cheers

Sean

**Comment by SturdyErde** [comment]
Great. I don't have that level of permissions on this repo. The issue will need to be closed by either you or @boostchicken.
