### ISSUE TITLE
Missing /mnt/data/on_boot.d folder.

### ISSUE THREAD

**Issue by Tntdruid** [boostchicken/udm-utilities#94]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**UDM Information**
 - Variant [e.g. Dream Machine, Dream Machine Pro] Pro
 - Firmware Version: [e.g. 1.6.3, 1.7.2-rc4] 1.8.5
 - Controller Version [e.g 5.14.9] 6.0.43

**Additional context**

Did the install dpkg -i udm-boot_1.0.2_all.deb,

i dont have the /mnt/data/on_boot.d on my UDM Pro.

I did reboot it after the install.

First time installing stuff on my UDM Pro :)

**Comment by spali** [comment]
Was the `dpkg -i ...` command successfully?
Could you paste the output here so we can see what happened?

**Comment by Tntdruid** [comment]
root@ubnt:/# dpkg -i udm-boot_1.0.2_all.deb
[parse_pkg_files] cmdargs:  dpkg
(Reading database ... 56190 files and directories currently installed.)
Preparing to unpack udm-boot_1.0.2_all.deb ...
Unpacking udm-boot (1.0.2) over (1.0.2) ...
Setting up udm-boot (1.0.2) ...
#-> ubnt-dpkg-cache install
[parse_pkg_files] cmdargs:  dpkg
[cache_add_action] PKGFILES:  /udm-boot_1.0.2_all.deb
removing /data/dpkg-cache/stretch/packages/udm-boot_1.0.2_all.deb ... done
udm-boot: action=install, package=/data/dpkg-cache/stretch/packages/udm-boot_1.0.2_all.deb mark=manual
<-# ubnt-dpkg-cache install

**Comment by spali** [comment]
that's strange...there doesn't seem to be any error.
Is it possible that you checked the existence of `/mnt/data/on_boot.d` from within the `unifi-os shell`?
if the prompt is `root@ubnt:/#` then you are inside the unifi container.
If so, you need to drop out of the unifi container with exit.
Then you are in the shell of the UDM (host) itself. Should be visible by only a `#` as prompt. 
There you should see it. Otherwise please do a `ls -l /mnt/data/`  and post the result.

**Comment by Tntdruid** [comment]
Welcome to UniFi Dream Machine!
# ls -l /mnt/data/
total 56
drwxr-xr-x    2 root     root          4096 Aug 12 20:44 crash-data
drwxr-xr-x    2 root     root          4096 Jan  8 12:10 log
drwx------    2 root     root         16384 Apr  3  2019 lost+found
drwxr-xr-x    2 root     root          4096 Jan  6 17:43 on_boot.d
-rwxr-xr-x    1 root     root           129 Jan  8 22:11 on_boot.sh
drwx------    3 root     root          4096 Apr  3  2019 podman
drwxr-xr-x    2 root     root          4096 Apr  3  2019 ssh
drwxr-xr-x    3 root     root          4096 Jan  7 12:16 system
drwxr-xr--    2 root     root          4096 Jan  7 12:21 traces
drwxr-xr-x    4 root     root          4096 Jan  8 09:10 udapi-config
drwxr-xr-x    8 root     root          4096 Aug 20 23:57 unifi-os

**Comment by spali** [comment]
There it is :)

**Comment by Tntdruid** [comment]
Thanks for the help 👍
