### ISSUE TITLE
Cut a release now that the reboot bug has been fixed.

### ISSUE THREAD

**Issue by JKomoroski** [boostchicken/udm-utilities#95]
#71 has been fixed by #86 

Can we cut a release of version 1.0.3 and update relevant documentation?

**Comment by xeor** [comment]
@boostchicken do you got time for carving out a 1.0.3 release? The issue this is referring to is breaking peoples install :(

**Comment by boostchicken** [comment]
This is done!  There is now a url that redirects to latest always https://udm-boot.boostchicken.dev
