### ISSUE TITLE
add https://hub.docker.com/r/scyto/unifibrowser to cool things in readme.md

### ISSUE THREAD

**Issue by scyto** [boostchicken/udm-utilities#96]
I see you have my multicast-relay added in cool things - thanks for that!

You might want to consider this https://hub.docker.com/r/scyto/unifibrowser too (it actually has more pulls and is more popular)

I can fork and create a PR for the readme if you want.

You call, nice repo of links and tools!

**Comment by SturdyErde** [comment]
Add a PR, and I'll test!

**Comment by boostchicken** [comment]
@scyto I am happy to add you as a contributor here if you want to put some of your projects here or just keep the readme's up to date with your latest hijinx :) Jump in the slack (at the top of the README.md) and let me know
